### ISSUE TITLE
Limit number of results returned by lookup and auto load additional results when user scrolls to bottom of list

### ISSUE THREAD

**Issue by silkentrance** [crucialfelix/django-ajax-selects#105]
@crucialfelix 

In our app we have > 100k names of persons that we would like to be able to search for using ajax_selects.

The current implementation would, in worst case scenarios, result in a major performance drop as the lookup would return far too many items.

I am currently working on a PR that will

 - load only a given number of items from the server with each request (limit)
 - load additional items from the server as soon as the user scrolls down to the bottom of the list (offset)

I still need to flesh things out but I wonder whether such a PR would be appreciated and how soon it could be integrated into the master once all issues have been resolved.

Thanks!

**Comment by crucialfelix** [comment]
honestly I would build a custom interface for something like that. write a
django view for it, make an angular or react view to handle it.
I'm not sure how jquery-ui handles the scrolling and repopulating.  a popup
like this isn't the best interface.

but also why do you say that it would return all the results ? it certainly
doesn't. I have 600k items on one site and the search works fine.
you will run into performance problems of course if the indexes aren't
efficient.
its the Lookup that is responsible for fetching results, nothing about
django-ajax-selects does this. so you can customize that query as you like.

**Comment by silkentrance** [comment]
Granted, however, entering a term of a min length of 1 and some common character like for example 'a' will return you most of your data from the server, especially when you look up multiple attributes in your model, e.g. first_name, last_name, country, city etc.

The PR will eventually prevent such situations from ever occurring as it will incrementally load results from the server. Just have a look, the changes made are minimal and will not change the overall behaviour of the app/api.

And using angular is not an option here, believe me, way too complicated for the folks responsible for implementing the application...

**Comment by crucialfelix** [comment]
https://github.com/crucialfelix/django-ajax-selects#plugin_options-property-default

plugin options: minLength

**Comment by silkentrance** [comment]
I know that, but not everyone likes to limit their searches by this option. In our use case, there is no restriction on minLength.

**Comment by crucialfelix** [comment]
then do it in your Lookup.  if its only one char then just return YourModel.objects.none()

**Comment by silkentrance** [comment]
Doing it in just the lookup will limit the results to an artificial limit and will not allow the user to retrieve more results from the same query by simply scrolling down the list.

**Comment by silkentrance** [comment]
Doing it in the lookup requires an alternative implementation of the JQuery UI AutoComplete widget. I am currently working on this.

I think that this issue can be closed.
