### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'autocomplete' of undefined"

### ISSUE THREAD

**Issue by gudddu** [crucialfelix/django-ajax-selects#107]
Dear All,

I am getting an error upon using django_ajax_select. This happens as soon as the page is loaded and the error i seen in chrome Javascript console.

The error is indicated to be on this line of ajax_select.js

var proto = $.ui.autocomplete.prototype,
      initSource = proto._initSource;

The error is "Uncaught TypeError: Cannot read property 'autocomplete' of undefined"

I am using jquery-1.11.2.min.js and I have also includes the js that come with django_ajax_select viz
bootstrap.js and ajax_select.js

Please help. Below is the chrome screenshot.

![image](https://cloud.githubusercontent.com/assets/1304877/6408055/0c08b6cc-be23-11e4-9b7a-81a52cb6054d.png)

**Comment by crucialfelix** [comment]
Somehow you have not loaded all the javascript.

The best is to include the {{ form.media }} or if you are using the admin
then it should just work. you should not include anything.
Check the install directions again carefully.
Check what scripts the browser has actually loaded.

**Comment by raushanraj** [comment]
This happens because of ordering of js files in your template:
Correct Order of Js files:
   1.  <script src="{% static 'ajax_select/js/bootstrap.js'%}"></script>
    2 .  <script src="{%static 'ajax_select/js/ajax_select.js' %}"></script>
