### ISSUE TITLE
format_item_display - List Items showing up as object Object

### ISSUE THREAD

**Issue by gudddu** [crucialfelix/django-ajax-selects#109]
I am using django_ajax_select version='1.3.5' and Django 1.7.4

The listed items from the ajax search are not showing up formatted. 

They show up as in the image at http://imgur.com/BFAN60W 

This is depite that I have format_item_display method well written. 

Here is my format_item_display . . . I confirmed by adding a print statement that the values are correct.

def format_item_display(self,obj):
    """ (HTML) formatted item for displaying item in the selected deck area """  
    print escape(obj.vehicle_plate_number),escape(obj.transporter.name)
    return u"%s - %s" % (escape(obj.vehicle_plate_number),escape(obj.transporter.name))

Some additional data. I noticed in Chrome JS Console that the Ajax Call returns this response

[{"pk": "BDPJ34", "match": "BDPJ34 - SERVICIOS LOGISTICOS DGA S.A.", "value": {"transporter_name": "SERVICIOS LOGISTICOS DGA S.A.", "vehicle_plate_number": "BDPJ34"}, "repr": "BDPJ34 - SERVICIOS LOGISTICOS DGA S.A."}]

The response looks alright.

What could be missing? This may not be an issue but just something that I am not doing correctly.

I also noticed that when i render the form, it is adding two fields instead of one. I am rendering the form using this code.

{% for field in vehicle_search_form %}
            <div class="fieldWrapper">
  {{ field.errors }}
  {{ field }}
  </div>
{% endfor %}

And my lookup template is at http://dpaste.com/0XDT2E2

Appreciate your guidance.

**Comment by patri-badger** [comment]
I have the same issue. It looks like the `repr` value is ignored.
