### ISSUE TITLE
Not Secure.  invalid literal for long() with base 10

### ISSUE THREAD

**Issue by raushanraj** [crucialfelix/django-ajax-selects#114]
I just edit the values of ManytoManyField i.e;autocompleteselectmultiple.Using Firebug,i change the value field to   ##     value="|1|2@|" .I get 500 error. invalid literal for long() with base 10: '2@'

input type="hidden" data-plugin-options="{&quot;min_length&quot;: 1, &quot;html&quot;: true, &quot;source&quot;: &quot;/admin/lookups/ajax_lookup/university&quot;}" data-ajax-select="autocompleteselectmultiple" value="|1|" id="id_university" name="university"

**Comment by raushanraj** [comment]
![screenshot from 2015-03-28 23 34 13](https://cloud.githubusercontent.com/assets/3590763/6882210/0b5bc65a-d5a3-11e4-87ea-02e6537d5341.png)

**Comment by crucialfelix** [comment]
Fixed with the new release, though Django itself may throw invalidation errors with this input
