### ISSUE TITLE
Error with TheForm in Django 1.8

### ISSUE THREAD

**Issue by jonathanmorgan** [crucialfelix/django-ajax-selects#115]
When I try to start the django admins in a project that uses django-ajax-selects, I get a 500 error - the problem is in the call to make_ajax_form() that sets up an ajax select field:

ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TheForm needs updating.

There was a deprecation warning in 1.7 for this that referenced TheForm.  Looks like it has been deprecated.

**Comment by jonathanmorgan** [comment]
Looks like the problem is fixed in the code that is in the repo (ajax_select/__init__.py, line 95), so if the rest of the code is in an OK state, would just need to get a new version out that has line 95 as:

    fields = '__all__'

instead of:

    pass

I made this one change in the source of the version of django-ajax-selects that is on my machines (1.3.5), and that stopped the error.  Is this plugin in a state where you could put the latest up on pypi?

**Comment by misalabs** [comment]
It has been fixed on dev https://github.com/crucialfelix/django-ajax-selects/commit/6f12ba65440ab65356c7113b7af2ad5dc4ed10b6

There is the same issue https://github.com/crucialfelix/django-ajax-selects/issues/96#issuecomment-86826811

**Comment by crucialfelix** [comment]
Its out https://pypi.python.org/pypi/django-ajax-selects

**Comment by jonathanmorgan** [comment]
Works great for me on all the sites I control that use it (only three, but much appreciated!).
