### ISSUE TITLE
How to refresh on_deck after setting value of field programatically 

### ISSUE THREAD

**Issue by zobbo** [crucialfelix/django-ajax-selects#116]
Is it possible to do this? I have a dialog which has a much more evolved screen for selecting items from the dropdown if my users can't do a simple lookup. If the use the dialog I set the value of the underlying select field programatically. I can see it's set if I examine in the JS console but if I try and make the _on_deck section show the newly set value it doesn't happen. 

I've tried firing 'added' and 'change' triggers to it. 

Any ideas?

**Comment by jonathanmorgan** [comment]
I have this question, also - I'm using a django-ajax-select field as part of a content analysis coding form, to lookup a person based on name.  I have a field where the coder captures the name string, then a button that copies the name string over to the django-ajax-selects field.  The lookup doesn't fire until you go into the field and make an event, however.  I tried .keyup(), .click() and using .trigger() to trigger one o the javascript functions associated with the form input, but I have not yet been able to programmatically initiate a lookup.   Here is the event I'm using (with jquery):

    // javascript to copy name from #source-name to the Lookup text field.
    $( document ).ready(
        function()
        {
            $( '#lookup-source-name' ).click(        
                function()
                {
                    // declare variables
                    var source_text = "";
                    var person_lookup = "";
        
                    // get selection
                    source_text = $( '#source-name' ).val();
                    //alert( "source text : " + source_text );

                    // get lookup text field,  place value, then try to figure out how to initiate lookup.
                    person_lookup = $( '#id_person_text' )
                    person_lookup.val( source_text );
                    person_lookup.keyup()
                    //person_lookup.click()
                    //person_lookup.trigger('init-autocomplete');
                }
            )
        }
    );

**Comment by funkyfuture** [comment]
i think i'm more or less in the same situation like @zobbo. in my case i want to set an item from another window. it's almost working, however it's not very elegant since i have to replicate the code in `ajax_selects.js` from line 16 to 43. so, a convenience would be to have a trigger that gets the id of the target widget, the selected pk and its representation passed and then takes care as if an item has been selected manually.

disclaimer: i'm very fresh with javascript, so if this is already possible, i'd appreciate any hint on that. if not, i suggest to label this issue as a feature request.

**Comment by crucialfelix** [comment]
I'll look into it more, but you might try triggering the jquery autocomplete to do a select:

http://stackoverflow.com/questions/7633727/how-do-you-trigger-autocomplete-select-event-manually-in-jqueryui

There should be some way to do this, I just can't think of what it is right now.

**Comment by funkyfuture** [comment]
just a thought: there must be a mechanism that the is used from an 'add another'-popup, right? maybe that can be used.

if someone posts a helpful hint here, I'll commit a documentation update.

though I got my use-case working today, it was quiet a pita. most confusing was to figure out to attach events in the correct js-namespace.

**Comment by merutak** [comment]
I ended up with:
`$('#myAutocompleteField').trigger('didAddPopup', [new_id, new_text]);`

**Comment by jonathanmorgan** [comment]
What do you put in "`new_id`" and "`new_text`"?  Is `new_text` is the value you are searching for?

The following used to work for me, but something changed recently and "keydown" stopped working with no error:

    element_id = '#my_ajax_person_name_field'
    id_person_text_element = $( element_id );
    id_person_text_element.val( "test name" );
    id_person_text_element.trigger( 'keydown' );

**Comment by merutak** [comment]
@jonathanmorgan my code simulates a selection of a result, so I'm not searching, but choosing a value (which I could get from search or through any other place, e.g. a different API call). So 'new_id' is the value to be submitted with the form (if it's ever submitted), and 'new_text' is what the user should see (parallel to your LookupChannel's `format_item_display`).
