### ISSUE TITLE
Add another popup doesn't add `?_popup=1` to url in Django 1.8

### ISSUE THREAD

**Issue by unklphil** [crucialfelix/django-ajax-selects#118]
Using the included example, when adding a `Song` object at `http://localhost:8000/admin/example/song/add/`, there is a field for selecting a `Group` foreign key with a "+ add" link next to it.

In Django < 1.8, when clicking on the link, a popup opens with the url `http://localhost:8000/admin/lookups/add_popup/example/group?_popup=1` and when saving the `Group`, the popup closes and the `Group` field is populated in the `Song` form.

However in Django >= 1.8 the popup url is `http://localhost:8000/admin/lookups/add_popup/example/group` (note the missing `?_popup=1`) and when saving the `Group`, the popup redirects to the `Group` and doesn't populate the `Song` form's `Group` field.

~~Presumably some admin javascript changed in the Django 1.8 update, but I haven't yet tracked it down.~~

EDIT: It looks like the `showAddAnotherPopup`/`showRelatedObjectPopup` has [changed](https://github.com/django/django/blob/1.8/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L60) and it [no longer adds the _popup parameter](https://github.com/django/django/blob/1.7.7/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L59)

**Comment by crucialfelix** [comment]
That must be why it doesnt close itself and set the pk correctly. I noticed
this with 1.8 but didn't file the bug yet.

There are unit tests now so I hope to corner these annoying breakages and
keep it maintainable.

**Comment by splatEric** [comment]
I think the problem might be around detecting when an object is selected - I get the popup working fine, but when add_popup in the views tries to inspect the response text to look for dismissAddAnotherPopup it doesn't find it - I think the response model might have changed. No time to dig further now, but thought it might be useful to pass on ...

**Comment by splatEric** [comment]
This change seems to fix the problems with this functionality, but it might be a bit of a dirty hack, rather than the actual solution we should go with:

https://github.com/splatEric/django-ajax-selects/commit/f946a0aaf350e731391ee16a24eecf745dcaaae3

But if you're happy to bring it in, let me know and I'll send over the pull request.

**Comment by riklaunim** [comment]
Would be good to have Django 1.8 support.

**Comment by riklaunim** [comment]
So where is django-ajax-selects now? I see a lot of commits but no new release with Django 1.8/Py3.X support.

**Comment by crucialfelix** [comment]
The development branch has full support and I'm working on the release today

The previous release 1.3.6 supports Django 1.8 but with a deprec warning. Django 1.9 beta would not work, but it does work with the impending release.

Python 3 has been supported for many versions but one commit broke that. Now the tox tests check all pythons up to 3.5

**Comment by riklaunim** [comment]
nice :)

**Comment by crucialfelix** [comment]
1.4.0 came out on Sunday.  Sorry I forgot to announce here.

Check the docs, they are I think much better. Configuration is easier than
ever too thanks to autodiscovery.
