### ISSUE TITLE
Doesn't work with readonly_fields

### ISSUE THREAD

**Issue by int-ua** [crucialfelix/django-ajax-selects#120]
When field added simultaneously to AJAX form and to the `ro_fields` creating works fine but editing fails with

    AttributeError: 'NoneType' object has no attribute 'isnumeric'

**Comment by crucialfelix** [comment]
do you mean readonly_fields ?

**Comment by int-ua** [comment]
Yes.

**Comment by crucialfelix** [comment]
Fixed, release is imminent
