### ISSUE TITLE
Can't specify widget for AutoCompleteSelectMultipleField

### ISSUE THREAD

**Issue by rlskoeser** [crucialfelix/django-ajax-selects#126]
If you specify a widget option for AutoCompleteSelectMultipleField it is ignored and overwritten, but AutoCompleteSelectField will let you specify one (as long as it is the correct type). It looks like this might also be the case for AutoCompleteField.

This just needs to have the logic from AutoCompleteSelectField duplicated for the other init methods:
https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/fields.py#L125-L134

Alternatively or additionally, AutoCompleteField seems to allow passing in widget attributes  - making that work consistently for all the field classes would be useful and might remove the need for specifying the widget.

**Comment by crucialfelix** [comment]
There shouldn't really be a case where you specify a custom widget. This whole django-ajax-selects thing is basically just the widgets and processing what they return.

It was added 5 years ago: https://github.com/crucialfelix/django-ajax-selects/commit/475b79128b2dcfef67d086fa0ce8833cfcd131a8

and claims to be from issue 9, but that is incorrect. It would be better to remove the option entirely and make the code look more consistent on each one.

**Comment by rlskoeser** [comment]
@crucialfelix my use case was that I wanted to specify placeholder text for the input.  There was a way to do it for the select field but not the multiple select field, and since I couldn't do it consistently I had to skip it for now.

I agree, it would probably be better to remove the widget option and make the field objects consistent for passing widget attributes in.
