### ISSUE TITLE
documentation for add link on ajax fields for django admin inlines

### ISSUE THREAD

**Issue by rlskoeser** [crucialfelix/django-ajax-selects#127]
I have some autocompletes on django admin inlines and it took me forever to figure out how to get the add link button showing up - I guess maybe the normal logic that checks permissions and adds it doesn't get triggered in that case?  If it's possible for this to happen automatically, then maybe this is a bug.  Otherwise, it might be worth documenting so others don't have to hunt around for this.

I had to override get_formset on my inline admin class like this:

```
def get_formset(self, request, obj=None, **kwargs):
    formset = super(YourAdminClass, self).get_form(request, obj, **kwargs)
    autoselect_fields_check_can_add(formset.form, self.model, request.user)
    return formset
```

**Comment by crucialfelix** [comment]
Yes, it could be added to the docs here:

https://github.com/crucialfelix/django-ajax-selects#example

thanks

**Comment by crucialfelix** [comment]
thanks!
