### ISSUE TITLE
Content of input not included in field, only dropdown choices for make_ajax_field 

### ISSUE THREAD

**Issue by aaronkurtz** [crucialfelix/django-ajax-selects#134]
This is outside of the admin, so I'm using make_ajax_field and AutoCompleteSelectMultipleField, with the same result for both.

I have a form where the dropdown is very handy to show valid choices, but some users already know what they need to enter, so they type it in, hit enter, and are surprised when the form doesn't include what they typed in. They'd rather not take the time to click on the dropdown.

Including the content of the input with name="$field_text", not just the dropdown, into the field's output would allow quicker use of the form if the dropdown isn't needed.

**Comment by crucialfelix** [comment]
Does it not show the selected item below the input field ?

If the user wants to just type and hit enter then there needs to be a more javascript to support that. It means writing code that duplicates what jquery-ui does.

Understand that these are separate issues: how the item is selected and how the selected item is displayed.

**Comment by aaronkurtz** [comment]
The item is displayed below the input field. Clicking it or pressing down and hitting enter would add it to the list of selected items, but they want to just type and hit enter.

It'd be great to have this built in, but I've worked around the issue by having the form add the input's contents during field-specific cleaning. I do realize this causes some problems by throwing in possibly bad data from the input box, as opposed to the validated choices from the dropdown. Quick example below.

    def clean_devices(self):
        data_set = set(self.cleaned_data['devices'])
        from_input = self.data.get('devices_text', None)
        if from_input:
            try:
                extra = long(from_input)
                data_s.add(extra)
            except ValueError:
                raise forms.ValidationError('%(value)s is not a valid device.',
                    code='invalid_choice', params={'value': from_input})
        return list(data_s)

**Comment by crucialfelix** [comment]
I mean after its selected, then it is shown as a fixed item below the input box.  it does not stay in the input box.

in order to show the selected item in the input box I would switch the whole thing to use: https://select2.github.io/  and then it would be clearly shown that it was not just text that was typed in, but a selection that had been correctly resolved.  

but that would be essentially a different project and it would break any customizations that anybody has done.
