### ISSUE TITLE
AttributeError on invalid form data

### ISSUE THREAD

**Issue by hwkns** [crucialfelix/django-ajax-selects#135]
Similar to, but different from #120.

I have a test that submits invalid form data to a view (specifically, it is missing values for some fields, one of which is an `AutoCompleteSelectField`).

This *should* result in a Django `ValidationError` and `form.is_valid()` should return `False`.  But instead, `ajax_select` throws an `AttributeError`:

```python
  ...
  File "/var/www/project/project/app/views.py", line 904, in job_application_view
    if job_application_form.is_valid():
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/forms/forms.py", line 362, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/home/vagrant/.venv/lib/python3.4/site-packages/ajax_select/fields.py", line 111, in value_from_datadict
    return _as_pk(data.get(name, None))
  File "/home/vagrant/.venv/lib/python3.4/site-packages/ajax_select/fields.py", line 29, in _as_pk
    if got.isnumeric():
AttributeError: 'NoneType' object has no attribute 'isnumeric'
```

This library should not be allowing such low-level exceptions to bubble up.  It also should not be assuming that the data being passed into the form object is of the correct type and blindly calling `isnumeric()` without knowing if it's available.

**Comment by crucialfelix** [comment]
I think this might be the same as #120 

I shouldn't have accepted the pull request that added that check.  If you have even a fragment of your test that you could post here then that would help to set up a unit test and write the fix against it.

> This library should not be allowing such low-level exceptions to bubble up

In this case I think it really is a bug, so it should certainly raise the exception.

**Comment by hwkns** [comment]
It should be noted that the fix in https://github.com/crucialfelix/django-ajax-selects/commit/80a640a5e319d58467d992fe7a464386eb619e29 is very bad, because it destroys py3 compatibility (`unicode` is not defined in python 3).  Also, `isinstance()` is the preferred way to do type checking.  However, I think you were right in your comment on #117 -- I don't see any reason why the form field or widget should be doing this check.  I will see if I can distill my test down to something that could be used for this library.

**Comment by hwkns** [comment]
@crucialfelix I've made a pull request to remove the check.  I've run my tests against it and they pass.

**Comment by crucialfelix** [comment]
Thanks for the PR ! Its merged and there will be a new release shortly. 

I also finally got tox to run tests over all pythons and djangos
