### ISSUE TITLE
can't import register module

### ISSUE THREAD

**Issue by nielsonsantana** [crucialfelix/django-ajax-selects#139]
Can't import register module like: `from ajax_select impor register`
I using the version 1.3.6, but tried 1.3.5, 1.3.4, 1.3.3 and not work.

**Comment by crucialfelix** [comment]
Oh I'm sorry I updated the documentation today but that is the development branch which is for the upcoming release which will be 1.4.0

The documentation you should be look at it is here: https://github.com/crucialfelix/django-ajax-selects/tree/master

Sorry for the confusion

**Comment by nielsonsantana** [comment]
Thanks @crucialfelix!
