### ISSUE TITLE
fixed bug: AutoCompleteSelectMultipleField does not honor 'widget' parameter

### ISSUE THREAD

**Issue by taivo** [crucialfelix/django-ajax-selects#14]
`AutoCompleteSelectMultipleField` overwrites its `kwargs['widget']` with its default AutoCompleteSelectMultipleWidget so there it's not possible to customize the widget in your form definition.  

This seems to be a bug since the other ajax-select fields: `AutoCompleteSelectWidget` and `AutoCompleteField` both allow substituting the default widget with your own, just like django. Widget substitution is useful especially when you want to change placeholder attribute or CSS attributes of the default widget.

I have fixed it in this commit https://github.com/taivo/django-ajax-selects/commit/a24dc27fca488e49c15b1a8778451881617de086 but not sure how to submit a second pull request since I've already have one in the pipeline.

Last but not least, I find this package to be extremely useful. I wasted a lot of time getting autocomplete done on an adhoc basis, and even more time trying generalize all the adhoc code. Good thing I found ajax-select before going too far into reinventing the wheel. So thanks for maintaining this tool!

**Comment by qrilka** [comment]
Did you thought about adding something like https://github.com/Polyconseil/django-ajax-selects/commit/bccbcde7dea5170eeaf5749a3307b4639b58db8f ?

**Comment by crucialfelix** [comment]
That's a four year old fork with all the licensing information removed.

Django widgets already support attrs={'placeholder': 'Placeholder Text'}

so there is no need for a special hook.

https://docs.djangoproject.com/en/1.8/ref/forms/widgets/

widget is supported so you can create the widget with any attrs you want
including class, autofocus, disabled, maxlength etc.

http://www.w3schools.com/tags/tag_input.asp

maybe including a widget_attrs argument just like plugin_options would be a
good feature.

**Comment by qrilka** [comment]
Yes, that was the point - I don't see how could I set placeholder with e.g. `make_ajax_field`
