### ISSUE TITLE
Templates not included in pypi1.4.0 package

### ISSUE THREAD

**Issue by riklaunim** [crucialfelix/django-ajax-selects#141]
Seems like MANIFEST.in needs

recursive-include ajax_select/templates *

**Comment by crucialfelix** [comment]
Oh grrrr.  Fixed and a new release is out. I've downloaded and double checked it

Python packing is so annoying. I had to read all this stuff to figure out why it doesn't even read the MANIFEST.in instead it was reading this from 2013:

reading manifest file 'django_ajax_selects.egg-info/SOURCES.txt'
 Oct  6  2013 django_ajax_selects.egg-info


Thanks for the report !
