### ISSUE TITLE
Inline forms raise TypeError when not filled in

### ISSUE THREAD

**Issue by unklphil** [crucialfelix/django-ajax-selects#142]
In the example project in the repo, it is impossible to add a group, because if any of the inline forms' ajax fields are left empty, a `TypeError: 'NoneType' object is not iterable` is raised.

This can be replicated by running the example project and trying to add any item that has an inline form with an ajax field and not filling in any of the inline form fields.

**Comment by crucialfelix** [comment]
thanks, I've got a fix for this.

but now the inline forms are raising errors for missing required values. even though I'm not adding any. hmm

**Comment by crucialfelix** [comment]
But it still cannot save them. I've just wasted another hour of my life wandering through the jungle of Django's admin/forms/formsets/fields.

Why is a blank inline form considered to be bound ? Maybe because the pk of the parent object was set in the initial values.

Why is the inline form even being validated ? Maybe just to check if it is being inserted.

But what makes it considered as an insert ?

**Comment by Harper04** [comment]
Is there a workaround? I am also running into this issue but dont have the time to help fixing it :(. I removed all ajax_selects from all inlines for now...

**Comment by crucialfelix** [comment]
I really wish I could figure it out myself.  I have no idea why Django thinks they are filled out.

**Comment by jonathanmorgan** [comment]
If you'd like some help debugging, I'm seeing this, too.  I will try to poke around a bit and see if I can doctor the HTML to get it to not create the empty rows.

**Comment by jonathanmorgan** [comment]
Well, guess I should tell you what I'm seeing - in the admin, where the ajax select field is inside an inline, when you save the main record, the admin is creating empty rows in the table that joins the main record to the child record for each of the empty inline forms that contains an ajax-select field.

**Comment by crucialfelix** [comment]
Yep, I've tested it previously and seen that behavior. It doesn't have to do with the html or form structure

Its something that Django admin is doing.

**Comment by jonathanmorgan** [comment]
OK.  I'll have time to take a look at it early next week. I have copies of django 1.8 and 1.9 running the same application, I'll see if there is any difference between the two, as well.

**Comment by crucialfelix** [comment]
The best way to solve this is to set up a unit test that isolates this problem. Then tox runs it against all django versions.

The easiest way to fiddle about and test by hand is to us the example app. You can install django1.8 and the example app already has an inline one to test with.

**Comment by roscue** [comment]
I am also running into the issue since upgrading from django 1.7 to django 1.8.

**Comment by unklphil** [comment]
Using git bisect, I was able to find the commit that introduced the problem: a37766905911b4d529b13dbcf384eb6e2f0d8a71

```
a37766905911b4d529b13dbcf384eb6e2f0d8a71 is the first bad commit
commit a37766905911b4d529b13dbcf384eb6e2f0d8a71
Author: crucialfelix <crucialfelix@gmail.com>
Date:   Tue Nov 3 14:25:51 2015 +0100

    fix #123 - changed_data always includes AutoComplete fields

    it was because the fields are CharFields so they return pk of u'1'
    but the initial value is 1

:040000 040000 bc551af142a5fb40f6d5679d27bf65baa0a1093d f60cea81db168a95af513f971530be524304a7a7 M	ajax_select
:040000 040000 0035720d1877e964de9d8fc5629e8b7e7afce25e c6fa9494d76f0cd3fcabd0bae0115b35a0975275 M	tests
```

**Comment by unklphil** [comment]
Based on this, it seems that the empty inline fields' `initial_value` is `None` but the `data_value` is `u''`, so what is effectively being compared for empty fields in [`AutoCompleteSelectField.has_changed`](https://github.com/crucialfelix/django-ajax-selects/blob/63e58497e136562a038873feeb6645f8b08d4c3e/ajax_select/fields.py#L145) is `u'None' != u''`, which ends up returning `True`.

**Comment by crucialfelix** [comment]
What really needs to happen is to change AutoCompleteSelectField parent class from CharField to ModelChoiceField. Then it should fetch the actual models and compare those as the parent class does it.

This is the root of quite a few problems: the field parent class is wrong. Its not a text field.

**Comment by jonathanmorgan** [comment]
Just wanted to let you know this appears to have fixed the issues my clients were having.  Thank you!

**Comment by crucialfelix** [comment]
All praise to @unklphil

**Comment by unklphil** [comment]
Haha, fixed it out of necessity :) I'm glad I could help.
