### ISSUE TITLE
template extension doesn't work properly

### ISSUE THREAD

**Issue by mengjiin** [crucialfelix/django-ajax-selects#144]
I'm using django-ajax-selects 1.4.1 and Django 1.8.7.
I followed the documentation to extend the template:

// yourapp/templates/ajax_select/autocompleteselect_{channel}.html
{% block extra_script %}
<script type="text/javascript">
$("#{{html_id}}_on_deck").bind('added', function() {
var id = $("#{{html_id}}").val();
console.log('added id:' + id );
});
$("#{{html_id}}_on_deck").bind('killed', function() {
console.log('removed');
});
</script>
{% endblock %}

The issue is that while the content of autocompleteselect_{channel}.html shows up in my form, the content of autocompleteselect.html does NOT.

In ajax_select/fields.py:
        templates = ('ajax_select/autocompleteselect_%s.html' % self.channel,
                    'ajax_select/autocompleteselect.html')
        out = render_to_string(templates, context)

render_to_string only renders the first template, which is autocompleteselect_{channel}.html. It does not render autocompleteselect.html.

My workaround is to put the whole content of autocompleteselect.html into autocompleteselect_{channel}.html.

I'd appreciate if someone looks into this.

Thanks!

**Comment by crucialfelix** [comment]
Sorry, I will make that part in the docs clearer.

What you need to do is extend the original template and customize the blocks you need.

it should be the first line in your template file:

```
{% extends "ajax_select/autocompleteselect.html" %}

{% block extra_script % }
// custom stuff for this block here
{% endblock %}
```

https://docs.djangoproject.com/en/1.7/topics/templates/

**Comment by funkyfuture** [comment]
the documentation also states that the channel is *prefixed* to the template's filename.
