### ISSUE TITLE
Is the guide incomplete, or am I missing something?

### ISSUE THREAD

**Issue by Alphare** [crucialfelix/django-ajax-selects#155]
Hi everyone.
I'm sorry to have to post this to issues, but I don't know of another way.
I posted my problem on SO, at [this link](http://stackoverflow.com/questions/35017961/i-cant-seem-to-make-django-ajax-selects-work), but nobody answered.
Thank you in advance.

**Comment by crucialfelix** [comment]
I think you are missing the {{ form.meta }}

you have the ajax selects js in there, but you need the other ones
included. jquery-ui and the css

but I will check it out tomorrow and answer the SO question




On Tue, Jan 26, 2016 at 10:57 PM Raphaël Gomès <notifications@github.com>
wrote:

> Hi everyone
> I'm sorry to have to post this to issues, but I don't know of another way
> I posted my problem on SO, at this link
> <http://stackoverflowcom/questions/35017961/i-cant-seem-to-make-django-ajax-selects-work>,
> but nobody answered
> Thank you in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crucialfelix/django-ajax-selects/issues/155>.
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by Alphare** [comment]
@crucialfelix : Thank you for your reply. I actually was missing these files... maybe it should be written in the documentation for dummies like me?
I have a 403 error in the console now... I think it's because I'm missing a csrf token in the ajax, but I included it in the form. Does the form has to be named "form"?

**Comment by crucialfelix** [comment]
It used to be in the old guide. I guess I accientally remove that.

I'll put it in here:
http://django-ajax-selects.readthedocs.org/en/latest/Outside-of-Admin.html

**Comment by Alphare** [comment]
@crucialfelix : I have updated my SO question with the 403 error. Thanks again.

**Comment by Alphare** [comment]
I no longer have this issue. No idea what caused it or how it was fixed... maybe something on my host's side... anyway, thanks.

**Comment by Alphare** [comment]
@crucialfelix I'm having a 403 error again. I have no idea what changed it, since I did not alter the lookups, or the url, or anything...

**Comment by Alphare** [comment]
@crucialfelix : I ran a debug on my lookup, and it appears I was missing a "check_auth" method to allow users other than staff to use the lookup. I wish it'd been more obvious in the Quick Setup from the doc.
Thanks for your help.

**Comment by crucialfelix** [comment]
OK, I will add some text about that. Don't close this issue, I'll close it when I've updated the docs.

thanks !
