### ISSUE TITLE
Additional stacked inlines clear un-saved autocomplete fields

### ISSUE THREAD

**Issue by mlewis-sandow** [crucialfelix/django-ajax-selects#156]
I have an admin form that has stacked inlines containing autocomplete select fields. Adding an additional row triggers init-autocomplete. If someone fills out the autocomplete field then adds a row without saving then init-autocomplete gets triggered for the un-saved autocomplete select field and clears it.

Has anyone dealt with this? I tried changing:

    $('input[data-ajax-select=autocompleteselect]').each(function (i, inp) {
      addAutoComplete(inp, function ($inp, opts) {
        $inp.autocompleteselect(opts);
      });
    });

to:

    $('input[data-ajax-select=autocompleteselect][value=""]').each(function (i, inp) {
      addAutoComplete(inp, function ($inp, opts) {
        $inp.autocompleteselect(opts);
      });
    });

so that only empty fields are initialized but then of course you cannot change the field after saving.

**Comment by crucialfelix** [comment]
which version are you using ? this bug was fixed in the last release.

**Comment by mlewis-sandow** [comment]
Ah, of course that did it. I got a little mixed up because I had forked. Thanks!
