### ISSUE TITLE
Pass kwargs to `make_ajax_field`

### ISSUE THREAD

**Issue by joshblum** [crucialfelix/django-ajax-selects#164]
I'm trying to add a `label` to override a `verbose_name` but I noticed that the `kwargs` are not passed form `make_ajax_form` to `make_ajax_field`
https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/helpers.py#L58

Is there a reason for this? I can submit a patch to fix, just wanted to check if it was intentional first

**Comment by crucialfelix** [comment]
Those are kwargs for making the form, not for making a specific field. So it would be a mess to pass in all those kwargs to each and every field.

You would want to pass in verbose_name and then you would get that name on each field in the form.

Don't use the make_ajax_form  - its a simple helper function. Make a normal form and make each field that you need using make_ajax_field and pass your custom args there.

**Comment by joshblum** [comment]
Gotcha, thanks!!
