### ISSUE TITLE
Wrong parsing of id's in LookupChannel.get_objects

### ISSUE THREAD

**Issue by homaralex** [crucialfelix/django-ajax-selects#167]
Adding a foreign key leads to an error.

Line 100 in https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/lookup_channel.py
`return [things[aid] for aid in ids if aid in things]` - the part `if aid in things` returns `False`, because `ids`
is a list of strings, and `things` is a `int` indexed dictionary

**Comment by crucialfelix** [comment]
This was fixed quite a while ago. The ids are coerced to the pk type: https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/lookup_channel.py#L97

**Comment by dancastellani** [comment]
Seems that the pk_type is not being discovered correctly on Django 1.11.

My inherited model falls into the correct clause at https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/lookup_channel.py#L97, however the type cast does not work to transform the '22' into an id 22 (cast to int).

On Django 1.11, seems that the solution is to use: `self.model._meta.pk.remote_field.field.target_field.to_python`. I'm not sure if this would work on Django 2+.

I hope that helps someone using Django 1.11.
