### ISSUE TITLE
model.lookups.ExampleLookup object at 0x253ea90> cannot find object:3

### ISSUE THREAD

**Issue by cgara** [crucialfelix/django-ajax-selects#168]
Hi,

In admin cant save an objetc.
Error: example.lookups.ExampleLookup object at 0x253ea90> cannot find object:3
Configuration:
Lookup:
class ExampleLookup(LookupChannel):

    model = Pessoa
    min_length = 3
    def get_query(self, q, request):
        return Example.objects.filter(Q(first_name__icontains=q) |Q(email__istartswith=q)).order_by('first_name')

    def get_result(self, obj):
        """ result is the simple text that is the completion of what the person typed """
        return obj.first_name+' '+obj.last_name

    def format_match(self, obj):
        """ (HTML) formatted item for display in the dropdown """
        return "%s<div><i>%s</i></div>" % (escape(obj.first_name+' '+obj.last_name), escape(obj.email))
        
    def format_item_display(self, obj):
        """ (HTML) formatted item for displaying item in the selected deck area """
        return "%s<div><i>%s</i></div>" % (escape(obj.first_name+' '+obj.last_name), escape(obj.email))

form:
class ExampleForm(forms.ModelForm):
    example= AutoCompleteSelectField('example', required=True, help_text=None)

settings

AJAX_LOOKUP_CHANNELS = {

    'example': ('example.lookups', 'ExampleLookup'),

}

Regards

**Comment by luis8** [comment]
@cgara Not sure if you managed to fix it but i debugged the app and find the problem

This method below is here 
https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/lookup_channel.py#L100


    def get_objects(self, ids):
        # return objects in the same order as passed in here
        pk_type = self.model._meta.pk.to_python
        ids = [int(pk_type(pk)) for pk in ids]
        things = self.model.objects.in_bulk(ids)
        return [things[aid] for aid in ids if things.get(aid)]

The list expression wont find anything because the 'ids' are in a string and the 'things' return the key value as an int, but adding an int to the 'ids' list expression fix it at least in django==1.9.7 which is the version i'm using

If you still having issues i'd recommend monkey patching

**Comment by crucialfelix** [comment]
`int(pk_type(pk))` is non-sensical.  pk_type is casting the id to the correct type that the field uses.  by casting that again to an int you are assuming that it is supposed to be an int and breaking all other usages.

**Comment by crucialfelix** [comment]
Sorry, I now it's been many months. I don't have enough information here to know what you are doing or what the context of that error message is. 

If you are still having an issue then please reopen this issue.
