### ISSUE TITLE
Making django-ajax-selects work with two ForeignKeys, one limiting the other?

### ISSUE THREAD

**Issue by d33tah** [crucialfelix/django-ajax-selects#169]
Suppose I have the following two fields:

```
Vendor: (xyz)
Product (abc)
```

I'd like to limit a choice of products based on vendor selected. Is there a way to do that on django-ajax-selects so that if user selects a vendor "ACME", only products tied to "ACME" would be displayed as an option. If so, could you point me to the relevant piece of documentation?

I also asked this question on StackOverflow: http://stackoverflow.com/q/37302484/1091116

**Comment by crucialfelix** [comment]
There isn't any built in system to do that. You can implement it yourself.

see:
https://github.com/crucialfelix/django-ajax-selects/issues/166
