### ISSUE TITLE
Using different field for value to be stored

### ISSUE THREAD

**Issue by cheluis** [crucialfelix/django-ajax-selects#171]
ajax_lookup only uses primary key and this is the value stored on hidden input. What about if the fields used is a CharField and dev wants to store, lets say, a slug instead of the model's primary key? Am I missing some configuration step or it is not possible to do?

**Comment by crucialfelix** [comment]
AutoCompleteSelectField  is for selecting another model by the ForeignKey and it always uses the primary key. That is how the two objects are joined in the database. This isn't anything that django-ajax-selects does, it's how django stores ForeignKeys: by the primary key of the other model. If the other model is using a string as primary key then it *should* store that.

If you are using [AutoCompleteField](https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/fields.py#L353) then it is a text field and it stores a string. That doesn't guarantee that there is another model with a slug or anything at all really - it is just a string.

**Comment by cheluis** [comment]
AutoCompleteField also search makes a search request to some lookup channel object right? But just stores the string representation of the selected object right?

**Comment by crucialfelix** [comment]
Yes. You control what that representation is (what the string is) by the lookup channel

**Comment by cheluis** [comment]
Thanks, looking forward to collaborate in this project.
