### ISSUE TITLE
From where shoud I extends

### ISSUE THREAD

**Issue by kaldown** [crucialfelix/django-ajax-selects#172]
Despite #144 it's still unclear what exact mediasets should be applied to custom form for makein django-ajax-selects work.

Just adding all staticfiles from /admin solve the problem, but it's a dirty way.
only jqeury-ui/jqiery.min.js isn't enough.

Could you be more precise about what must be in templaet?

**Comment by crucialfelix** [comment]
Just this:

```
{% extends "ajax_select/autocompleteselect.html" %}

{% block extra_script % }
// custom stuff for this block here
{% endblock %}
```

This is for a custom template for the widget. It doesn't sound like that is what you are trying to do.
There is no media in that template, there should not be.  That is not the page, that is just rendering a single field.

If you are making a custom form and putting it on a page that is not in the admin then you need `{{ form.media }}`

**Comment by kaldown** [comment]
Actually I can't understand either how to do this, and can't find any reliable answer. Morethan, Your example app is not working (very one custom form).
I think that would be helpful for others, if someone point here how to basically render form with ajax-field.

````
# form.py
class QuestionSchemaForm(forms.ModelForm):
    class Meta:
        model = QuestionSchema
        fields = ('name', 'questions')

    #questions = AutoCompleteSelectMultipleField('select_questions')
    questions = make_ajax_field(Question, 'name', 'select_questions')
````

````
lookup.py
@register('select_questions')
class QuestionLookup(LookupChannel):

    model = Question
    #min_length = 4

    def get_query(self, q, request):
        result = self.model.objects.filter(name__icontains=q)
        return result[:20]

````

````
QuestionPool.html
{% extends 'base.html' %}

{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        {{ form.media }}
        <input type="submit" value="submit">
    </form>
{% endblock %}

````
P.S. `base.html` - my base with jquery, bootstrap, jquery-ui and other staff which must be present.

Thanks a lot for suggestion.

P.S. awesome app witch I found completelly useful for adminpage even with zero knowledges about async javascript. But faced too much trouble, so I quickly read about how ajax works to implement in all other pages, but want to defeat my misunderstanding for such a nice project!

**Comment by kaldown** [comment]
Yeap, that was completely stupid question )
All I need it's to input `ajax_select.js` from `staticfiles/` dir
