### ISSUE TITLE
Using ajax selects for filtering related items in admin?

### ISSUE THREAD

**Issue by chozabu** [crucialfelix/django-ajax-selects#175]
ajax-selects solves the problem of massive dropdowns being generated inside models in django admin brilliantly

Can it already be used to solve massive "list filters" when one of the same models is added to a modeladmins "list_filter"?

I am currently using `RelatedOnlyFieldListFilter`  but autocomplete would be much better

**Comment by crucialfelix** [comment]
No sorry. That is a whole different system and there isn't any simple way to reuse the code for that.

Generally speaking if the list filters is huge then it isn't a good candidate for a filter UI. I would say that it's the wrong UI to use for that.

You might look into using the search box in the django admin. I think you can write custom handlers for that; not sure. Check the django docs.
