### ISSUE TITLE
Allow for more flexible result templates

### ISSUE THREAD

**Issue by AlexHill** [crucialfelix/django-ajax-selects#179]
Hi,

I'm using django-ajax-selects to dynamically add rows to an inline formset. To reduce duplication, I use the same template fragment to render the form rows on initial page load as to render the items added by django-ajax-selects. What this means is that the string returned by my lookup's `format_item_display()` already contains its on_deck id attr and a kill button.

This works really well – the only problem is that I have had to override `ajax_select.js` to modify the `addKiller` function to account for a `repr` that already contains those things, instead of adding the kill button and wrapping `repr` in a div unconditionally.

Before preparing a pull request I wanted to check: would you be likely to accept this change?

Thanks!

**Comment by AlexHill** [comment]
In addition to the change described above, I'd like to change `reset()` to only delete elements that have actually been added by the plugin, instead of emptying the entire deck.

**Comment by crucialfelix** [comment]
Well probably that would increase complexity and documentation and I really want to avoid that. The formatting is supposed to be just for the items, not the ui.

You wouldn't want a different ui for each model.
