### ISSUE TITLE
Prefer document.createElement to document.write

### ISSUE THREAD

**Issue by tdphillips** [crucialfelix/django-ajax-selects#182]
Checking dev tools on a site making use of django-ajax-selects using Chrome >= 53 results in a warning that `document.write`s might be blocked in certain contexts.

![2016-10-07-095946_776x113_scrot](https://cloud.githubusercontent.com/assets/3379265/19193167/0a959ea8-8c77-11e6-9b37-e31f97153c7e.png)

[A bit more info is available here.](http://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/) If you determine this is worth doing, I've got some code I can put up. It's a fairly simple change.

**Comment by crucialfelix** [comment]
I saw that warning too. That would be most welcome if you can do a pull request for that.
