### ISSUE TITLE
No cache management headers in HTTP response

### ISSUE THREAD

**Issue by Bartvds** [crucialfelix/django-ajax-selects#187]
There are no cache headers set on the search results so the browser and caching layers could serve stale results, or do repeated calls for same term.

This can be worked around with some decorators in the urls.py or solved upstream but it feel like an oversight to have nothing in here. Maybe this should be configurable; depending on where you use this functionality you may want some or zero caching.

Note the admin (using django 1.9) sets `Cache-Control: max-age=0, must-revalidate, no-store, no-cache;` on it's own HTML output.

**Comment by crucialfelix** [comment]
Good idea, we should set http headers.
