### ISSUE TITLE
Ocassionally: $.ui.autocomplete is undefined

### ISSUE THREAD

**Issue by gregmuellegger** [crucialfelix/django-ajax-selects#188]
I just upgraded to 1.5.1 and tested locally, I reloaded the admin change page a couple of times and got in quite a few instances, the following error message:

![image](https://cloud.githubusercontent.com/assets/88278/19468675/047f3836-9518-11e6-9887-7ceb0bf85f7b.png)

That happens already on page load, before I focus the input.
Cache has been emptied and once in a while it works as expected. I assume that the autocomplete plugin is not loaded in time before the ajax-selects code is executed.

**Comment by crucialfelix** [comment]
I've been seeing this sporadically too in production. 

It seems that window load event fires before all scripts are loaded.

caused by this change: https://github.com/crucialfelix/django-ajax-selects/commit/dea45993cbeb107cbce35b8d25e06f1678d3a9f3

I'll do a fix shortly. Hopefully today.

**Comment by crucialfelix** [comment]
I am seeing this on our production server.  Unfortunately I could never replicate it locally.

Locally, with a throttled connection:

![screen shot 2016-10-19 at 12 31 52](https://cloud.githubusercontent.com/assets/218738/19518098/89d0942e-9605-11e6-983b-9b5e3466260e.png)

jquery-ui is the last to load, and ajax_select.js doesn't run until the window 'load' event. No problem.

But what if jquery-ui arrives before jquery ?

Logically speaking what was missing was to set the two scripts to `script.async = false;`

https://www.html5rocks.com/en/tutorials/speed/script-loading/

> Scripts that are dynamically created and added to the document are async by default, they don’t block rendering and execute as soon as they download, meaning they could come out in the wrong order. However, we can explicitly mark them as not async.

Therefore this should work:

    var script = document.createElement('script');
    document.head.appendChild(script);
    // doesn't block rendering while downloading
    // adds to sequential execution queue
    // so they run after document is loaded
    script.async = false;
    script.src = src;

They should run one after another.

But in other situations there are a lot more scripts on the page and on one admin page I see up to 4 !!! jquerys. Oh dear.

![screen shot 2016-10-19 at 12 33 54](https://cloud.githubusercontent.com/assets/218738/19518206/3a68e96c-9606-11e6-8791-1b928d28495f.png)

At least on my site what happened is that jquery.ui arrived before the jquery 1.9.1 that ajax selects loads. It found a `window.jQuery`, attached itself to that. But then when `ajax_selects.js` runs it finds a different `window.jQuery` and there is no `.ui` attached to it.

So I've reverted to `document.write` which ensures that it blocks rendering, loads those two in the right order, then runs `ajax_selects.js` which sees the same window.jQuery. After that everything is isolated and it doesn't matter what everybody else does to window globals.

Going forward, I will switch to a build system that makes a single isolated bundle. Probably switch to select2 so it is smaller and has better ui. This will make releases easier and faster too.

The django admin is a jungle, it is best to stay out of it.

**Comment by crucialfelix** [comment]
For reference, this was the reason I tried to change from using document.write:

```
A Parser-blocking, cross-origin script, https://code.jquery.com/ui/1.10.3/jquery-ui.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
```
