### ISSUE TITLE
The autocomplete select doesn't behave expected

### ISSUE THREAD

**Issue by fuji246** [crucialfelix/django-ajax-selects#190]
The expected behavior will fill the the text input typing instead of adding deck below. And the Initial text should also fill the the text field instead of adding to deck. Adding to deck looks like more intuitive for multi selections.

I've made some changes locally to make it work

commend out deck in autocompleteselect.html

```
<!--<div id="{{html_id}}_on_deck" class="results_on_deck"><div>{{current_repr|safe}}</div></div>-->
```

In ajax_select.js, in "$.fn.autocompleteselect"

```
function receiveResult(event, ui) {
        if ($this.val()) {
          kill();
        }
        $this.val(ui.item.pk);
        //$text.val('');
        $text.val(ui.item.repr);
        $text.attr("size", $text.val().length);
        //addKiller(ui.item.repr, ui.item.pk);
        //$deck.trigger('added', [ui.item.pk, ui.item]);
        $this.trigger('change');

        return false;
      }

      function reset() {
        if (options.initial) {
          //addKiller(options.initial[0], options.initial[1]);
          $text.val(options.initial[0]);
          $text.attr("size", $text.val().length);
          $this.val(options.initial[1]);
        } else {
          kill();
        }
      }
```

maybe remove the killer as well

**Comment by crucialfelix** [comment]
There is the possibility that we will switch to https://select2.github.io/ later. That would show the stylized selection in the box. It also has a much better UI and less dependencies

But for the current releases I won't change it. That is the search box. The display area is below that. This is consistent for both select and select multiple.
