### ISSUE TITLE
How to get selected value to appear in text box, not on-deck area

### ISSUE THREAD

**Issue by pdbethke** [crucialfelix/django-ajax-selects#191]
Hello all,

I've implemented the ajax-selects library and it works great - except I'm unable to figure out how to have the selected value (I only need a single-select value) to stay in the text box, not move into the "on-deck" area. I've created separate template files as the docs suggest, and even split the javascript into a custom file to allow it to be overridden - but to no avail. Are there any examples out there that have the value stay bound to the type-in box? Thanks! 

Peter

**Comment by crucialfelix** [comment]
That would involve changing quite a bit of the design and code. 

If anything I might switch to Select2 at some point which has nice styling and UI and displays the selected items inline. That would get rid of jquery jqueryui and make it a lot more portable.

**Comment by artscoop** [comment]
And this, Chris, would be absolutely **great**.

**Comment by nelsontristao** [comment]
Any update on this?

**Comment by crucialfelix** [comment]
You can try one of these:

https://github.com/applegrew/django-select2
https://pypi.python.org/pypi/django-easy-select2

I don't see much point in rewriting this library to be a different library.
