### ISSUE TITLE
"required" attribute not being cleared when form field has a valid instance

### ISSUE THREAD

**Issue by tclancy** [crucialfelix/django-ajax-selects#193]
I'm in the process of upgrading a project from Django 1.5 to 1.10 and have upgraded from `django-ajax-selects` 1.3.3 to the latest (1.5.2) but am running into a problem: when I have a form field (single auto-complete) that has a valid instance either pre-added or added after page load, the `required` attribute on the visible field is not being updated correctly. In our existing codebase, the visible form field (i.e., not the hidden id field the Ajax select is actually populating) does not have a `required` attribute in these cases but in every version of this library from 1.4.3 to 1.5.2 the field is incorrectly marked as required. I don't see anywhere in the `helpers.py` or the `ajax-selects.js` where the required field is ever adjusted so I am wondering if something changed between 1.3.3 and more recent versions in the field/ form configuration that I am missing.

FWIW, I have tried upgrading jQuery and jQuery UI to the CDN versions shown in the example project to make sure it's not an issue there. We are also using Bootstrap and bootstrap.js

**Comment by crucialfelix** [comment]
Do you mean an html attribute:
```
<input type="text" name="usrname" required>
```

That is something that Django 1.10 is doing. I didn't know about that (still on 1.9)

https://docs.djangoproject.com/en/1.10/releases/1.10/

Required form fields now have the required HTML attribute. Set the new Form.use_required_attribute attribute to False to disable it.

We would need to change django-ajax-selects to create the widget with this required explicitly removed.

**Comment by tclancy** [comment]
Ah, that must be it, thanks! I spent a ton of time looking at everything but Django's core functionality. Can I simply adjust `make_ajax_field` to force that to `False` in all cases or is there more work to be done? I'm happy to submit a PR for this.

**Comment by crucialfelix** [comment]
I think that would be the correct approach: those text fields are not really on the django form, they are just being used as inputs. They should not be required.

A PR would be very much appreciated !

In the meantime, you should be able to supply required=False in the widget_options when making the field:

https://github.com/crucialfelix/django-ajax-selects/blob/develop/ajax_select/fields.py#L117

```python
thing = AutoCompleteSelectField('things', widget_options={'required': False})
```

same with AutoCompleteSelectMultipleField

**Comment by tclancy** [comment]
`thing = AutoCompleteSelectField('things', widget_options={'required': False})`

Unless I am doing something wrong, that returns `TypeError: __init__() got an unexpected keyword argument 'required'`

>is your field required ? do you require something to be entered there ?

Yes, the field is required, so it feels like the ideal solution would be to make the required attribute depend on whether there is an instance or not.

**Comment by crucialfelix** [comment]
The required attribute should not be used ever here - it isn't a real input, it is a UI element and the real input is the hidden one with the pk.

Try:
``python
