### ISSUE TITLE
AutoCompleteSelectField shows help_text twice times.

### ISSUE THREAD

**Issue by robertomorati** [crucialfelix/django-ajax-selects#196]
Problem:

When added help_text messange in the AutoCompleteSelectField, it's appear twice times in the template.

**Comment by crucialfelix** [comment]
Which django version ?

**Comment by robertomorati** [comment]
Django version 1.10.6.
I fixed it:

In class AutoCompleteSelectField (line 118):

'''
 def __init__(self, channel, *args, **kwargs):
        self.channel = channel
        widget_kwargs = dict(
            channel=channel,
            here>>>> help_text=_(as_default_help) if not kwargs.get('help_text') else '',
            show_help_text=kwargs.pop('show_help_text', True),
            plugin_options=kwargs.pop('plugin_options', {})
        )
        widget_kwargs.update(kwargs.pop('widget_options', {}))
        kwargs["widget"] = AutoCompleteSelectWidget(**widget_kwargs)
        super(AutoCompleteSelectField, self).__init__(max_length=255, *args, **kwargs)
'''

**Comment by crucialfelix** [comment]
Set the option `show_help_text` to False.

http://django-ajax-selects.readthedocs.io/en/latest/Forms.html#make-ajax-field

If you are showing the field in a separate form (not in  the admin) then you need help text to be shown. If it is in the admin then it will be shown twice. Maybe Django 1.10 changed the behavior.

**Comment by robertomorati** [comment]
Hi @crucialfelix 

I really appreciate you attention!

I used the make_ajax_field and worked fine.  However, when I use the make_ajax_field or AutoCompleteSelectField I have another little problem, as you can see on the image below:

![problem_button](https://cloud.githubusercontent.com/assets/3457738/23898909/c71f29c2-0891-11e7-92fc-9fcc620bea2e.png)

Thanks,

**Comment by crucialfelix** [comment]
is the css included ?  what button is this ?

**Comment by robertomorati** [comment]
Hi @crucialfelix ,

Thanks for the attention!

Yes, all needed is included.
The django-ajax-selects is used in other parts of the project without problem.
In console is displayed (I don't no why yet):

**_Uncaught TypeError: Cannot read property 'length' of undefined choosen.jquery.min.js_**

I will debug to try find the problem.

**Comment by robertomorati** [comment]
Hi @crucialfelix ,

Sorry for the delay.
The problem with the button was because I didn't remove the javascript from chosen when enabled autocomplete.

I really appreciate the attention,
