### ISSUE TITLE
AjaxSelectConfig.ready() erases all previously registered by @register lookups (registry.load_channels())

### ISSUE THREAD

**Issue by MrYoda** [crucialfelix/django-ajax-selects#197]
python 3.5
django==1.9.12
django-ajax-selects==1.5.2

using `@register` in `admin.py` of my apps

**Comment by crucialfelix** [comment]
Don't use it in the admin, use it in yourapp/lookups.py

Django will load the lookups, and it will load the admins.  Don't confuse it by putting lookup stuff in your admin.

**Comment by MrYoda** [comment]
Ok, but it is so strange behaviour, imho.
I debugged it step-by-step: when interpreter execute line with `@register` - pair "lookup name - lookup class" been added to registry. But when apps ready occurs - AppConfig.ready() handler erases all registry entries and try to load lookups again.

**Comment by crucialfelix** [comment]
It is kind of normal behavior. When django starts up it runs the startup configs for each of the installed apps.  

First it initiates the admin and during that you have gone and registered things in ajax selects lookups. Then it initiates ajax selects which clears the registry and then loads all lookups.py files.  

Thus you really are not supposed to be putting @register inside your admin.py files. It is the wrong place for them.
