### ISSUE TITLE
Allow to pass what field I want to make_ajax_field

### ISSUE THREAD

**Issue by hovi** [crucialfelix/django-ajax-selects#199]
I like make_ajax_field, because it takes care of label, help_text and other stuff. But I cannot make field of different kind (ex: use AutoCompleteField instead of AutoCompleteSelectField).
Would be cool to add another optional parameter, passing what kind of field do I want to use. It would also allow using 3rd party fields inherited from existing ones.

Something like:
```
def make_ajax_field(related_model, fieldname_on_model, channel, show_help_text=False, field_class=None, **kwargs):


.....

    if field_class:
        f = field_class(
            channel,
            **kwargs)
    else:
        if isinstance(field, ManyToManyField):
            f = AutoCompleteSelectMultipleField(
                channel,
                **kwargs)
        elif isinstance(field, ForeignKey):
....
```

**Comment by crucialfelix** [comment]
https://github.com/crucialfelix/django-ajax-selects/blob/b0f8584df71a9a5673ac323405882a2adb149f3b/ajax_select/helpers.py#L66

If you want to customize then you should just write it out the way you want it. Or make your own function that does what you want. If we just add lots of options then it gets confusing and that make a simple easy to use function into a headache. It's just a helper function.

**Comment by hovi** [comment]
Yeah fair enough.
