### ISSUE TITLE
How to get entries via ModelForm?

### ISSUE THREAD

**Issue by kierun** [crucialfelix/django-ajax-selects#201]
I have a model which contains: `allowed_users = models.ManyToManyField(User, blank=True)`. In the `ModelForm`, I define:

```
    allowed_users = AutoCompleteSelectMultipleField(
        'AllowedUsers',
        required=False,
        help_text=u'A set of users allowed to use this code.')
```

and `lookups`:

```
@register('AllowedUsers')
class AllowedUsers(LookupChannel):  # pragma: no cover
    """This is a lookup channel.

    No need to unit test it.

    http://django-ajax-selects.readthedocs.io/en/latest/index.html
    """

    model = User

    def get_query(self, q, request):
        return self.model.objects.filter(
            is_active=True).filter(
                username__contains=q).order_by('username')

    def format_item_display(self, item):
        return u"<span class='user'>{}: {}</span>".format(
            unicode(item), item.get_full_name())
```

In my view, I save the objects created by the above form using:

```

        if form.is_valid():
            new = form.save(commit=False)
            # […]
            new.save()
```

However, no matter how many entries I add using the `allowed_users`, none of them show in the final `new` object. 

Any idea what I am doing wrong?

**Comment by kierun** [comment]
I just tried this via the admin interface and it works just fine. It is just my custom form that does not convert it. How odd… ☹

**Comment by crucialfelix** [comment]
Maybe post more of your form. I can't see anything besides that you saved the object.

**Comment by kierun** [comment]
The problem was that you cannot save a `ManyToMany` key unless your object has a `pk` key. So, by using `new = form.save(commit=False)`, I was shooting myself in the foot as new does not have an id yet. This only happens when you save it.

The solution was to save the `new` object, then inspect the form fields to get the usernames:

```
        if form.is_valid():
            new = form.save(commit=False)
            # I am doing "clever" things with the new object here,
            # like setting a creator and created date/time…
            new.save()
            for usr in form.cleaned_data['allowed_users']:
                new.allowed_users.add(usr)
```

**Comment by crucialfelix** [comment]
Ah yeah. See the bit about save_m2m and commit=False:  https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/

**Comment by kierun** [comment]
Thanks!
