### ISSUE TITLE
Using make_ajax_form for m2m fields fails

### ISSUE THREAD

**Issue by nwp90** [crucialfelix/django-ajax-selects#204]
Using make_ajax_form and specifying a field which is a reverse m2m (i.e. specified on the other end) causes failure `AttributeError: 'ManyToManyRel' object has no attribute 'verbose_name'`. Relevant part of traceback:

```
  File "/project/cm/api/admin.py", line 191, in OutcomeAdmin
    form = make_ajax_form(Outcome, {'presentations': 'presentation'})
  File "/project/env/src/django-ajax-selects/ajax_select/helpers.py", line 58, in make_ajax_form
    f = make_ajax_field(model, model_fieldname, channel, show_help_text)
  File "/project/env/src/django-ajax-selects/ajax_select/helpers.py", line 92, in make_ajax_field
    kwargs['label'] = _(capfirst(force_text(field.verbose_name)))

```

**Comment by crucialfelix** [comment]
Which django version ?

It should only support m2m, not any reverse relationship. Does your other model have a foreign key to the model you are editing ?
