### ISSUE TITLE
Uncaught ReferenceError: showAddAnotherPopup is not defined

### ISSUE THREAD

**Issue by jpbullalayao** [crucialfelix/django-ajax-selects#208]
This happens in the `autocompleteselectmultiple.html` when clicking on the add button:
```
<a href="{{ add_link }}" class="add-another addlink" id="add_{{ html_id }}" onclick="return showAddAnotherPopup(this);"> add!</a>
```

So, I assume this is because my page doesn't see `showAddAnotherPopup` defined anywhere in the JavaScript, however my page does have these imports:

```
<script type="text/javascript" src="/static/ajax_select/js/bootstrap.js"></script>
<script type="text/javascript" src="/static/ajax_select/js/ajax_select.js"></script>
```

Any guidance on this would be very appreciated! Thanks!

**Comment by crucialfelix** [comment]
If you are using the admin then it should include those.  If you are outside the admin  see: http://django-ajax-selects.readthedocs.io/en/latest/Outside-of-Admin.html

which django, ajax_selects versions ?
