### ISSUE TITLE
search_fields like in ModelAdmin

### ISSUE THREAD

**Issue by Remiremi** [crucialfelix/django-ajax-selects#21]
I think search_field should be replaced by a search_fields that works like the one in the ModelAdmin. It would make django-ajax-selects more consistent with the django API.

Here is how it can be achieved. I mostly adapted code from django/contrib/admin/views/main.py. I also added support for ordering.

    import operator
    from django.db.models import Q
    from django.contrib.admin.util import lookup_needs_distinct
    from ajax_select import LookupChannel

    class LookupChannelExtended(LookupChannel):

        def __init__(self, *args, **kwargs):
            self.lookup_opts = self.model._meta
            self.root_query_set = self.model.objects.all()
            super(LookupChannel, self).__init__(*args, **kwargs)

        def get_ordering(self, request, queryset):
            """
            Returns the list of ordering fields. First we check the object's default
            ordering. Then, any manually-specified ordering overrides anything.
            Finally, a deterministic order is guaranteed by ensuring the primary key
            is used as the last ordering field.
            """
            ordering = []
            if self.lookup_opts.ordering:
                ordering = self.lookup_opts.ordering
            if hasattr(self, 'ordering'):
                ordering += list(self.ordering)
            # Ensure that the primary key is systematically present in the list of
            # ordering fields so we can guarantee a deterministic order across all
            # database backends.
            pk_name = self.lookup_opts.pk.name
            if not (set(ordering) & set(['pk', '-pk', pk_name, '-' + pk_name])):
                # The two sets do not intersect, meaning the pk isn't present. So
                # we add it.
                ordering.append('pk')

            return ordering

        def get_query(self, query, request):
            qs = self.root_query_set
            use_distinct = False

            # Set ordering.
            ordering = self.get_ordering(request, qs)
            qs = qs.order_by(*ordering)

            # Apply keyword searches.
            def construct_search(field_name):
                if field_name.startswith('^'):
                    return "%s__istartswith" % field_name[1:]
                elif field_name.startswith('='):
                    return "%s__iexact" % field_name[1:]
                elif field_name.startswith('@'):
                    return "%s__search" % field_name[1:]
                else:
                    return "%s__icontains" % field_name

            if self.search_fields and query:
                orm_lookups = [construct_search(str(search_field))
                               for search_field in self.search_fields]
                for bit in query.split():
                    or_queries = [Q(**{orm_lookup: bit})
                                  for orm_lookup in orm_lookups]
                    qs = qs.filter(reduce(operator.or_, or_queries))
                if not use_distinct:
                    for search_spec in orm_lookups:
                        if lookup_needs_distinct(self.lookup_opts, search_spec):
                            use_distinct = True
                            break

            if use_distinct:
                return qs.distinct()
            else:
                return qs

You can now do something like this:

    class MemberLookup(LookupChannelExtended):
        model = Individual
        search_fields = ('first_name', 'middle_name', 'last_name')
        ordering = ('last_name', 'first_name')

**Comment by crucialfelix** [comment]
Because you can define any LookupChannel that you want, you are welcome to use your extended class.  Rather than make the django-ajax-selects more complicated, its better to allow people to innovate with their own code.
