### ISSUE TITLE
2 or more 'make_ajax_forms' on admin change sheet require 'save and continue editing'

### ISSUE THREAD

**Issue by johnnycakes79** [crucialfelix/django-ajax-selects#210]
Hi @crucialfelix, great tool.

However, I've hit a bug that I don't see as being solved by previous issues (I think).

When I  use 2 or more 'make_ajax_forms' on an admin change form - after using/selecting a choice in one of the widgets I have to  click 'save and continue editing' before I can get any action from the other select widgets...

```
@register('roles')
class RolesLookup(LookupChannel):
    model = models.Role

    def get_query(self, q, request):
        return self.model.objects.filter(code__icontains=q).order_by('code')[:5]

    def format_item_display(self, item):
        return u"<span class='tag'>{} {}</span>".format(item.code, item.name)
```

```
@register('users')
class UsersLookup(LookupChannel):
    model = get_user_model()

    def get_query(self, q, request):
        return self.model.objects.filter(Q(first_name__icontains=q) | Q(last_name__icontains=q)).order_by('first_name')

    def format_item_display(self, item):
        return u"<span class='tag'>{} {}</span>".format(item.first_name, item.last_name)
```
```
@admin.register(models.Lesson)
class LessonAdmin(ImportMixin, ExportMixin, VersionAdmin):
    form = make_ajax_form(models.Lesson, {
        'author': 'users',
        'audience':'roles',
    })
```
Thanks in advance,
J.

**Comment by crucialfelix** [comment]
Where do you use make_ajax_forms twice on the same admin ?  That sounds very strange. An admin should and can only have one form. I see only one form in your example as well.

You do have two fields on that form.  There should be no interaction or problem with that. You can have as many fields with ajax_select on them as you like.

**Comment by crucialfelix** [comment]
Maybe post your Lesson model.

**Comment by johnnycakes79** [comment]
Thanks for the quick feedback, indeed I have only one form with 2 fields (sometimes more) in the admin.py.

This is the model:
```
class Lesson(models.Model):
    LESSON_LEVEL = (
        ("1", "1"),
        ("2", "2"),
        ("3.1", "3 Block I"),
        ("3.2", "3 Block II"),
        ("3.3", "3 Block III"),
    )
    LESSON_TYPE = (
        ("1", "Classroom "),
        ("2", "E-Learning"),
        ("3", "Practical/OJT"),
        ("4", "Self-Study"),
    )
    title = models.CharField(db_index=True, max_length=50, blank=True, null=True)
    author = models.ForeignKey(User, db_index=True, blank=True, null=True)
    level = models.CharField(max_length=20, null=True, choices=LESSON_LEVEL)
    details = models.TextField(max_length=300, blank=True, null=True)
    url = models.URLField('URL', max_length=300, blank=True, null=True)
    lesson_type =  models.CharField('Type', max_length=20, null=True, choices=LESSON_TYPE)
    expected_duration = models.IntegerField(null=True, blank=True, help_text='Enter value in weeks.')
    audience = models.ManyToManyField(Role)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
```

BTW, I'm using Grappelli as an admin skin, don't know if that's an issue...

J.

**Comment by crucialfelix** [comment]
There isn't any problem at all with multiple ajax fields on a form. 

Note that in fact you can have multiple forms if you are using inline many to many. Those are form classes although on the html page there will only be one parent <form> tag.  Ajax selects works fine with this.

So I'm not sure what the issue is you are having. It may be something to do with grapelli, I have no experience using that. Re-open this is you have some detail about a bug.
