### ISSUE TITLE
Rendering widget with UUID (JSON not serializable, TypeError)

### ISSUE THREAD

**Issue by kut** [crucialfelix/django-ajax-selects#211]
If object PK is UUID, the function `make_plugin_options` tries to do `json.dumps` on a dict wth a UUID object inside, which is not JSON serializable.

We'd be able to get around this super simply if we set line 82 of fields.py to be:
```
initial = [current_repr, str(obj.pk)]
```
instead of:
```
initial = [current_repr, obj.pk]
```

Thoughts?

**Comment by kutakdogan** [comment]
This issue should actually be fixed with PR #206, so no need. Any idea when this will be sent to master branch?

**Comment by crucialfelix** [comment]
I will get a release out tomorrow

**Comment by kutakdogan** [comment]
Thank you!

**Comment by crucialfelix** [comment]
Released ! (2 days late)  Thanks !
