### ISSUE TITLE
Broken Django 1.11 compatibility

### ISSUE THREAD

**Issue by mhindery** [crucialfelix/django-ajax-selects#214]
The changelog for 1.6.* claims compatibility with Django 1.11. However, the widgets don't accept the  new `renderer` argument on the `render()` method.

This breaks code like this:

```python
class CustomAutoCompleteSelectMultipleWidget(AutoCompleteSelectMultipleWidget):
    def render(self, name, value, attrs=None, *args, **kwargs):
        # custom code
        return super(CustomAutoCompleteSelectMultipleWidget, self).render(name, custom_value, attrs, *args, **kwargs)
```

In order to make it work, I had to add `kwargs.pop('renderer')` before calling the `super()` method. This is quite an ugly hacky way to get it work.

**Comment by crucialfelix** [comment]
Really ? I wonder how it passed the tests. I will take a look at this.

**Comment by crucialfelix** [comment]
Can you post something small that shows this new `renderer` argument being used ? 

Is it something to do with this: https://docs.djangoproject.com/en/2.0/ref/forms/renderers/

**Comment by jonathanmorgan** [comment]
In django 2.1, when I use the following form code to make an ajax-selects widget on a page:

    class ArticleCodingForm( forms.ModelForm ):

        '''
        Create a form to let a user look up the source.
        '''

        class Meta:
            model = Article_Subject
            fields = [ "person", ]

            #exclude = [ 'article_data', 'original_person', 'match_confidence_level', 'match_status', 'capture_method', 'create_date', 'last_modified', 'source_type', 'subject_type', 'name', 'verbatim_name', 'lookup_name', 'title', 'more_title', 'organization', 'document', 'topics', 'source_contact_type', 'source_capacity', 'localness', 'notes', 'organization_string', 'more_organization' ]

        # AJAX lookup for person.
        person  = make_ajax_field( Article_Subject, 'person', 'coding_person', help_text = "" )

    #-- END ModelForm class ArticleCodingForm --#

I now get the following error:

    Request Method: | POST
    -- | --
    https://research.local/research/sourcenet/article/code/
    2.1
    TypeError
    render() got an unexpected keyword argument 'renderer'
    /home/jonathanmorgan/.virtualenvs/research/lib/python3.6/site-packages/django/forms/boundfield.py in as_widget, line 93
    /usr/bin/python3
    3.6.5
    ['/home/jonathanmorgan/work/django/research',  '/home/jonathanmorgan/.virtualenvs/research/lib/python36.zip',  '/home/jonathanmorgan/.virtualenvs/research/lib/python3.6',  '/home/jonathanmorgan/.virtualenvs/research/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/jonathanmorgan/.virtualenvs/research/lib/python3.6/site-packages',  '/home/jonathanmorgan/work/django/research']
    Tue, 7 Aug 2018 01:33:56 +0000

I can make the error go away by either:

- reverting to django 2.0.8
- in django 2.1, not rendering that form, which is just the ajax selects field, in the page in question.

Any thoughts on how I could troubleshoot or fix this?

Thanks,

Jonathan

**Comment by jonathanmorgan** [comment]
Also, looks like it is happening to all django-ajax-selects form fields in the admin proper, also, in my project using django 2.1.  Everywhere I have a django-ajax-selects field I get the error above when I try to load the page.  Reverting to django 2.0.8 makes it all work.

**Comment by crucialfelix** [comment]
This was fixed and released back in August. Thanks for the bug report !
