### ISSUE TITLE
Make input field wider

### ISSUE THREAD

**Issue by Smosker** [crucialfelix/django-ajax-selects#216]
Hello! Can someone advise me how to make input field wider? Maybe some parameter in lookup channel?

**Comment by crucialfelix** [comment]
Use css

**Comment by Smosker** [comment]
Thanks, that helps, but it changes width for all fields, that if i want to change width only to specific lookups?

**Comment by crucialfelix** [comment]
Django admin surround each field in the form with a unique element id based on the field name. The form itself is surrounded by some class or element id with the model name. Inspect the DOM. You should be able to find some way to uniquely specify the field you want and change the width.
