### ISSUE TITLE
I can't find static files

### ISSUE THREAD

**Issue by brayan15** [crucialfelix/django-ajax-selects#223]
Can you help me please? I can't find static files, on my console appear this:

(index):56 GET http://test.localhost:8000/static/ajax_select/js/bootstrap.js 404 (Not Found)
(index):57 GET http://test.localhost:8000/static/ajax_select/js/ajax_select.js net::ERR_ABORTED
(index):64 GET http://test.localhost:8000/static/ajax_select/css/ajax_select.css net::ERR_ABORTED

Also I'm using django material to admin. ty

**Comment by tejak96** [comment]
Hi. Can you tell me know how you fixed this issue?

**Comment by crucialfelix** [comment]
make sure you have included `ajax_select` in your settings.config APPS

**Comment by brdacost** [comment]
I did include the ajax_select on my INSTALLED_APPS settings, but I keep getting these errors both on and outside admin pages. Any other ideas why might be causing the issue?
