### ISSUE TITLE
Django 2.0 Compatibility issue

### ISSUE THREAD

**Issue by iAyaz** [crucialfelix/django-ajax-selects#224]
Is there quick fix?

'ManyToManyField' object has no attribute 'rel'
ajax_select/fields.py in autoselect_fields_check_can_add, line 442

**Comment by crucialfelix** [comment]
I will update the test matrix and run it with 2. Then it is fairly easy to find the fix without breaking all the other ones.

If you want to experiment then look at the tox file: https://github.com/crucialfelix/django-ajax-selects/blob/develop/tox.ini#L23

thanks,

**Comment by chirdeeptomar** [comment]
Refer https://code.djangoproject.com/ticket/24317

**Comment by crucialfelix** [comment]
I'll get in this PR shortly. Thanks for the help everybody !

**Comment by psam44** [comment]
Same issue with `AttributeError: 'AutoField' object has no attribute 'rel'`
Warning up to Django 1.11:
`"Usage of field.rel has been deprecated. Use field.remote_field instead."`

Revolved with these changes done in lookup_channel.py/get_objects() :
```
        # if self.model._meta.pk.rel is not None:
        if self.model._meta.pk.remote_field is not None:
            # Use the type of the field being referenced
            # pk_type = self.model._meta.pk.rel.field.to_python
            pk_type = self.model._meta.pk.remote_field.field.to_python
```
May need some additional code for backwards compatibility with older Django versions.

**Comment by crucialfelix** [comment]
PR is merged, release should come shortly

**Comment by iAyaz** [comment]
Happy new year to all.
Thank you guys.

**Comment by crucialfelix** [comment]
Released, thanks so much everybody !
