### ISSUE TITLE
1.7.0 release but no update to changelog.

### ISSUE THREAD

**Issue by TurnrDev** [crucialfelix/django-ajax-selects#229]

**Comment by crucialfelix** [comment]
Sorry about that. The changelog generator I was using before refused to work and I decided it was more important to ship the release now then solve it then. People were waiting.

short changelog for 1.7.0:

**Django >=1.8, <=2.1**

There are no other breaking changes or API changes.

I will update the changelog, thanks for complaining !

**Comment by JayTurnr** [comment]
Oops my bad! I feel bad now.

**Comment by crucialfelix** [comment]
Oh, don't feel bad at all ! You are totally correct. I honestly had forgotten all about it. I will update the changelog, and it's really important when it goes up a version like that.  

I meant "thanks for complaining" with a little bit of humor in there.

**Comment by JayTurnr** [comment]
Oh my bad! Sorry for closing the issue too aha I genuinely hit the wrong button.
