### ISSUE TITLE
Working properly in admin but not in view

### ISSUE THREAD

**Issue by Nyrio** [crucialfelix/django-ajax-selects#230]
Hi,

I'll quickly show the problem and then the details. Everything's working well in admin interface:
![image](https://user-images.githubusercontent.com/17441062/38645413-a7240fac-3dec-11e8-907b-1fb0ee210a1f.png)

But not when doing the same thing in a form on the website:
![image](https://user-images.githubusercontent.com/17441062/38645683-a1cf9052-3ded-11e8-90a4-4f3fcf0edc23.png)

The html is what is should be (the tags are present, I mean) but nothing is happening when I type.  And impossible to add any tag... Moreover, the "add" link appears only after going in admin interface and using the widget there.

------

Working with Python 3.6.5, Django 2.0.2, and this package 1.7.0.

------

I have defined the following lookup:
```
@register('tags')
class TagsLookup(LookupChannel):

    model = Tag

    def get_query(self, q, request):
        return self.model.objects.filter(name__icontains=q).order_by('name')[:50]

    def format_item_display(self, item):
        return u"<span class='tag'>%s</span>" % item.name
```

It is used in a `ModelForm`:
```
class MyForm(forms.ModelForm):
    tags = AutoCompleteSelectMultipleField('tags', required=False)

    class Meta:
        model = MyModel
        fields = [..., "tags"]
```

And the form is used both in admin and in a view:
```
@admin.register(MyModel)
class MyModelAdmin(AjaxSelectAdmin):
    form = MyForm
```
and
```
class MyView(generic.FormView):
    form_class = MyForm
    template_name = "mytemplate.html"
    success_url = "/"

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect("/accounts/login")
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
```

The template is the following:
```
{% extends "base.html" %}
{{ form.media }}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Save" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}
```

I've been checking everything again and again for hours now and can't seem to find what's wrong. Am I doing something wrong or is there a bug?

**Comment by Nyrio** [comment]
Oh, my bad, I found that `{{ form.media }}` is never loaded since it is not in the block body...

With the following template, it works except for some display problems that I will try to solve now:

```
{% extends "base.html" %}

{% block body %}
    {{ form.media }}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Save" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}
```

**Comment by crucialfelix** [comment]
Django template inheritance is always really annoying and the source of so many bugs. 

Somebody should replace the whole things with a hyperscript style function system. https://github.com/hyperhype/hyperscript
