### ISSUE TITLE
Reverse for 'core_user_add' not found. 'core_user_add' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by redcricket** [crucialfelix/django-ajax-selects#234]
This really isn't an issue. I just don't understand how to use django-ajax-selects.  I thought I did and I got the example django project to work no problem.  I tried to adapt that example to my particular situation but I am missing something some where.  If you could please help me out by taking a look at my detailed question on [stackoverflow](https://stackoverflow.com/questions/50883378/why-does-my-django-ajax-select-not-work-core-user-add-is-not-a-valid-view-fun).

I should also mention that I decided to investigate using django-ajax-select to help out with a performance problem I ran into where I have a pulldown that has 400K elements.  I did change to using raw_id_fields to solve the performance issue but my users would really like to have a pulldown as there are so many potential selections.  Would django-ajax-selects fix the performance issue or will I still have a performance issue?

 Thank you!

**Comment by crucialfelix** [comment]
core_user_add is nothing to do with django-ajax-selects

it is something in the `sudorequests` app that you haven't configured correctly.  You are merely seeing the error when you are trying to use the admin, but it doesn't matter what page you are accessing. It has nothing to do with django-ajax-selects

NoReverseMatch at /admin/sudorequests/approvalcontrol/9/change/
Reverse for 'core_user_add'

**Comment by crucialfelix** [comment]
But yes, a pulldown with 400k elements will not work. That is exactly what django-ajax-selects solves.

**Comment by crucialfelix** [comment]
Glad to hear it !
