### ISSUE TITLE
Custom No search result

### ISSUE THREAD

**Issue by MiStErLu** [crucialfelix/django-ajax-selects#238]
Hi,

It is possible to "customize" the answer "No search result" ?
In my case, the message appear at the bottom of the page... ?

![no search result](https://user-images.githubusercontent.com/5516692/44945998-d6f77580-adf3-11e8-9685-9e0defdf1eaa.png)

Is there a way to see "No search result" like other result when we got one ?
Or i do something wrong ?

Best regards,
MiStErLu

**Comment by crucialfelix** [comment]
I'm not sure why it would be down there.  It does have a CSS class so you can apply your own styling to it and even replace the text (using css). 

The text is coming from jquery UI select. They do have some translation files that you can load (si c'est le probleme principal), but this is an older version of jquery ui.

Ideally we would use Select2 which is much better, but that changes this project so completely that it isn't the same thing anymore.
