### ISSUE TITLE
AutoCompleteSelectField On Formset

### ISSUE THREAD

**Issue by mullerivan** [crucialfelix/django-ajax-selects#241]
I just  create  a formset  that  include one  Search  field  agains  all  Users  but  it is not working , and not  throwing errors at all
any idea  how to handle  multiple  apparitions of  the same  field  on a form?

I have  another  Field  that use the same   AutoCompleteSelectField  and it  works  well, in the same form, is  just the one that  appears  in the formset,  actually  just the  second one, cause the  first  works  well 

Any idae  of  how can i fix it ?

**Comment by crucialfelix** [comment]
Each field has a unique name and you can have as many you want in a form.

Without seeing any code and I can't tell what might be wrong.  I hope you figured it out.

**Comment by mullerivan** [comment]
yes  was my  bad, sorry about  it  and thanks for  answering :)

**Comment by crucialfelix** [comment]
Sorry for the late response, super busy here. Did you figure it out ?

**Comment by mullerivan** [comment]
Sure was  something related  of what  you have done,
Vilen Danke :)
