### ISSUE TITLE
AutoCompleteSelectMultipleWidget.render `list(value)` doesn't work well with strings

### ISSUE THREAD

**Issue by u8sand** [crucialfelix/django-ajax-selects#242]
Noting this line: https://github.com/crucialfelix/django-ajax-selects/blob/5488b26c5e2137dc7e5155ec740406589f02e512/ajax_select/fields.py#L209

I had to patch it to this in my application:
```diff
- values = list(value)
+ values = value.split(',') if type(value) == str else list(value)
```

This is especially important if populating a form directly from .GET arguments, otherwise things like `12,3` become `1;2;,;3` instead of `12;3`.

**Comment by u8sand** [comment]
A derived Django Form is being constructed with the requests's GET arguments.

```python
class DerivedForm(django.forms.ModelForm):
  field = AutoCompleteMultipleWidget(...)

form = DerivedForm(request.GET.dict()) 
```

The GET parameters are naturally strings, in order for them to be interpreted as a list they should get split. A standard list constructor treats it as a list of characters.

**Comment by u8sand** [comment]
So I was instantiating a `ModelForm` from GET parameters to enable the form to get pre-populated.

```python
form = form_cls(initial=dict(self.request.GET.dict(), **{
  'authors': [self.request.user],
}))
```

Turns out something depends on `initial` being a `QueryDict`, not a normal `dict`.

Changing this to
```python
GET = self.request.GET.copy()
GET['authors'] = self.request.user
form = form_cls(initial=GET)
```

Made it work with the existing django-ajax-selects.

**Comment by crucialfelix** [comment]
Ah, good! I've run into that one before in other situations. The querydict has to support getlist or something like that.
