### ISSUE TITLE
Dropdown list position

### ISSUE THREAD

**Issue by kaliif** [crucialfelix/django-ajax-selects#244]
Any idea why list of choices opens in the top left corner instead of below/above text box?

**Comment by crucialfelix** [comment]
- Could you post a screenshot ? 
- Do you have other css on the page besides the Django Admin ? 
- What version Django ? 
- What Browser ?

**Comment by josefkorbel** [comment]
I think that is the same issue as this https://github.com/crucialfelix/django-ajax-selects/issues/237#issuecomment-416946397
