### ISSUE TITLE
CSS classes for jQuery click binding do not work for Django 2.1.3

### ISSUE THREAD

**Issue by nwp90** [crucialfelix/django-ajax-selects#247]
It seems that .inline-group now needs to be ._inline-group, in static/ajax_select/js/ajax_select.js line 243 (with Django 2.1.3) - otherwise #157 is back.

**Comment by crucialfelix** [comment]
If you can post a quick PR for that it would be splendid. Just add both the old and new classes and it will work for everybody. 

Thanks !

**Comment by nwp90** [comment]
Haven't retested the fix yet; am doing so now.

**Comment by nwp90** [comment]
Oops, don't think I left the old class in...

**Comment by nwp90** [comment]
Added back the original classes, testing now.

**Comment by nwp90** [comment]
Seems good with current Django, haven't tested with old Django version.

**Comment by crucialfelix** [comment]
Release 1.9.1 
https://pypi.org/project/django-ajax-selects/
Thanks again for the fix!
