### ISSUE TITLE
jquery problems in django 2.2 related to new media asset merge behavior

### ISSUE THREAD

**Issue by jsm296** [crucialfelix/django-ajax-selects#248]
After upgrading to django 2.2, I get the following in admin screens where I have ajax select fields:

    TypeError: $ is undefined[Learn More] ajax_select.js:5:3
        <anonymous> https://localhost/static/ajax_select/js/ajax_select.js:5
        <anonymous> https://localhost/static/ajax_select/js/ajax_select.js:1

Rolling back to Django 2.1.8 resolves it.  The only mention of jquery in the release notes is this - https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets:

    Merging of form Media assets

    Form Media assets are now merged using a topological sort algorithm, as the old pairwise merging algorithm is insufficient for some cases. CSS and JavaScript files which don’t include their dependencies may now be sorted incorrectly (where the old algorithm produced results correctly by coincidence).

    Audit all Media classes for any missing dependencies. For example, widgets depending on django.jQuery must specify js=['admin/js/jquery.init.js', ...] when declaring form media assets.

Any advice on how to resolve this would be greatly appreciated.

Thanks,

Jonathan Morgan

**Comment by jsm296** [comment]
In fields.py, updating `_media` to this:

    def _media(self):
        # unless AJAX_SELECT_BOOTSTRAP == False
        # then load jquery and jquery ui + default css
        # where needed
        js = ( 'ajax_select/js/bootstrap.js', 'ajax_select/js/ajax_select.js', 'admin/js/jquery.init.js' )
        try:
            if not settings.AJAX_SELECT_BOOTSTRAP:
                js = ('ajax_select/js/ajax_select.js', 'admin/js/jquery.init.js' )
        except AttributeError:
            pass
        return forms.Media(css={'all': ('ajax_select/css/ajax_select.css',)}, js=js)

Fixes the "$ is undefined" problem for `ajax_select.js`.  I am seeing some other oddities subsequently (search in a field, it pulls up results, but when it does, there is "TypeError: elem.getClientRects is not a function[Learn More]", and then whether you choose one or click outside the pop-up to navigate away, the spinning wheel loading image stays there and the field stops working), but I'm going to dig a little deeper when I have a bit more, will report back.

**Comment by jsm296** [comment]
I checked a separate install of django - search in a field, it pulls up results, but when it does, there is "TypeError: elem.getClientRects is not a function[Learn More]", and then whether you choose one or click outside the pop-up to navigate away, the spinning wheel loading image stays there.  The field still works, though.  If there is anything I can or should do on my end to test or if there is something I'm missing, please let me know.

Thanks,

Jonathan

**Comment by jsm296** [comment]
Also sorry, forgot version details: python 3.6.5 on ubuntu 18.04, django 2.2, original problem is with django-ajax-selects 1.7.1, the version I've been testing with is https://github.com/jsm296/django-ajax-selects.

**Comment by jsm296** [comment]
look like Django 2.2 is importing jquery 3, and jquery UI needs to be version 1.12 to work with JQuery 3: https://stackoverflow.com/questions/37914869/jquery-ui-error-f-getclientrects-is-not-a-function

**Comment by jsm296** [comment]
Hmmm.  Except that it is jquery 3.3.1 in django 2.1.8, also.  What I'm seeing in the Firefox web console:

In django 2.1.8:

    >> django.jQuery.fn.jquery
    <- "3.3.1"
    >> $
    <- function b()
    >> $.ui.version
    <- "1.10.3"

In Django 2.2:

    >> django.jQuery.fn.jquery;
    <- "3.3.1"
    >> $
    <-- undefined
    >> $.ui.version
    <-- ! TypeError: $ is undefined[Learn More]

**Comment by jsm296** [comment]
Updating the media function in fields.py to:

    def _media(self):
        # unless AJAX_SELECT_BOOTSTRAP == False
        # then load jquery and jquery ui + default css
        # where needed
        js = []
        js.append( 'admin/js/jquery.init.js' )
        try:
            if ( settings.AJAX_SELECT_BOOTSTRAP == True ):
                js.append( 'ajax_select/js/bootstrap.js' )
        except AttributeError:
            # settings.AJAX_SELECT_BOOTSTRAP not set, default to bootstrapping.
            js.append( 'ajax_select/js/bootstrap.js' )
        #-- END try...except --#

        js.append( 'ajax_select/js/ajax_select.js' )
        return forms.Media(css={'all': ('ajax_select/css/ajax_select.css',)}, js=js)

Seems to fix it.

In console, this results in:

    >> django.jQuery.fn.jquery;
    <- "3.3.1"
    >> $
    <-- function b()
    >> $.ui.version
    <-- "1.10.3"
    >> django.jQuery.ui.version
    <-- TypeError: django.jQuery.ui is undefined[Learn More]
    >> window.jQuery
    <- function b()
    >> window.jquery.fn.jquery;
    <- "1.9.1"

So, it looks like this puts everything back in the state it was in 2.1.8.  I haven't tested this in 2.1.8 to see if it causes a regression.  I will try to do that in a bit.

**Comment by jsm296** [comment]
I was able to quickly test, looks like this updated media class works in Django 2.1.8, also.

**Comment by jannero** [comment]
I'm also affected by this issue and jsm296's fix fixes issue.

**Comment by crucialfelix** [comment]
So if I understand correctly, there is no longer a window.jQuery loaded by Django admin unless at least one widget has requested it.

But the bootstrap does NOT work? (does not load jquery and assign to a global `$`)

https://github.com/crucialfelix/django-ajax-selects/blob/1b362f045b0b327426cbd5224cb742755974ed33/ajax_select/static/ajax_select/js/bootstrap.js#L22-L24

---

btw. simpler check without use of `AttributeError` would be:

```
if getattr(settings, "AJAX_SELECT_BOOTSTRAP", True):
    js.append("ajax_select/js/bootstrap.js")
```

https://github.com/crucialfelix/django-ajax-selects/blob/1b362f045b0b327426cbd5224cb742755974ed33/ajax_select/fields.py#L30-L40

**Comment by jannero** [comment]
Using latest Chromium (on Linux) I can see the following TypeError in JS console:

```
ajax_select.js:5 Uncaught TypeError: Cannot read property 'fn' of undefined
    at ajax_select.js:5
    at ajax_select.js:248
```

On line 248 there is `})();` and on line 5: `$.fn.autocompleteselect = function(options) {`

So to me it looks like that with the current ajax-select version jQuery is not assigned to global $

Also I was previously using Django 2.1 where things were working so a change in Django 2.2 has "caused" this issue.

Looking at the loaded resources, the following .js files (incomplete list) are loaded with current version of ajax-select (in my project):

- jquery.js
- bootstrap.s
- jquery.init.js
- ajax_select.js
- core.js
- RelatedObjectLookups.js

With change `if not settings.AJAX_SELECT_BOOTSTRAP` -> `if getattr(settings, "AJAX_SELECT_BOOTSTRAP", True)`:

- jquery.js
- jquery.init.js
- core.js
- bootstrap.js
- RelatedObjectLookups.js
- ajax_select.js

**Comment by crucialfelix** [comment]
Thanks for researching that! Now I understand a bit more.  

It still looks like it should load the old jquery if there is no `window.jQuery`.  Maybe Django now loads async?

I assume `bootstrap.s` is just a typo.

Does it work with the second load order you are showing above?

---

This package (django-ajax-selects) is using the hideously outdated jquery ui. Porting to something better means basically making a different library. 

jquery.ui is not guaranteed to work with the most recent jquery (the one that django might be supplying).

I do notice that django core now includes select2 which is what I would port to: https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/admin/static/admin/js/vendor/select2/select2.full.js

Core stuff like doing ajax lookups should be handled by Django's core admin and they should be able to upgrade and support as they put out new releases. Maybe they are intending to do that soon.

There are already separate packages that support it: https://github.com/applegrew/django-select2

django-ajax-selects has to support all these django versions and the frontend isn't even nice and modern for simple testing.

Personally I don't even use Django admin for new projects.

**Comment by crucialfelix** [comment]
Ah right, it's in Django since 2: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields

I'll add that to the readme.

What is stopping you from switching to Django's version?

**Comment by crucialfelix** [comment]
```python
def _media(self):
    js = ['admin/js/jquery.init.js']

    # Unless AJAX_SELECT_BOOTSTRAP == False
    # then load include bootstrap which will load jquery and jquery ui + default css as needed
    if getattr(settings, "AJAX_SELECT_BOOTSTRAP", True):
        js.append('ajax_select/js/bootstrap.js')

    js.append('ajax_select/js/ajax_select.js')

    return forms.Media(css={'all': ('ajax_select/css/ajax_select.css',)}, js=js)
```

But it doesn't make sense to me why it should include `jquery.init` but NOT Django's `jquery`.

The only thing that jquery.init is doing is settings window.django.jQuery = window.jQuery.

**Comment by jannero** [comment]
Ah, I had missed the autocomplete_fields in Django 2.

I do not have any barrier for using that. Thanks for pointing that out.

About the issue: The bootstrap.s was a typo, it should have been bootstrap.js like you suspected.

**Comment by jsm296** [comment]
Sorry coming back to this late, but I use this plugin in forms outside the admin, as well.  Do you know if autocomplete_fields work outside the admin, or of another option if they do not?  I must admit I'm putting off writing my own ajax fields until django-ajax-selects simply won't work anymore.

**Comment by amrishparmar** [comment]
> ```python
> def _media(self):
>     js = ['admin/js/jquery.init.js']
> 
>     # Unless AJAX_SELECT_BOOTSTRAP == False
>     # then load include bootstrap which will load jquery and jquery ui + default css as needed
>     if getattr(settings, "AJAX_SELECT_BOOTSTRAP", True):
>         js.append('ajax_select/js/bootstrap.js')
> 
>     js.append('ajax_select/js/ajax_select.js')
> 
>     return forms.Media(css={'all': ('ajax_select/css/ajax_select.css',)}, js=js)
> ```
> 
> But it doesn't make sense to me why it should include `jquery.init` but NOT Django's `jquery`.
> 
> The only thing that `jquery.init` is doing is setting `window.django.jQuery = window.jQuery`.

Is there any chance that the fix could be incorporated into a new release? The default `autocomplete_fields` feature is not a direct replacement for how we're using `django-ajax-selects`, so would be good to have this resolved officially.

**Comment by crucialfelix** [comment]
If somebody can make a PR then it is possible. Otherwise I'm afraid I'm overbooked right now.

**Comment by jsm296** [comment]
The way I fixed it is a little different, but I will make a pull request of that.  I have it tested and running in multiple production applications, so I know it works.

I also am working on using django-autocomplete-light, based on select2, as a replacement - [https://django-autocomplete-light.readthedocs.io/](https://django-autocomplete-light.readthedocs.io/).

I'll post what it took to migrate once I get it working.

**Comment by jsm296** [comment]
I updated my pull request to just use the code that @crucialfelix suggested and @amrishparmar quoted.  It looks like the Travis CI tests are failing.  Not sure if it is because of the code or something in the configuration.

**Comment by jsm296** [comment]
https://github.com/crucialfelix/django-ajax-selects/pull/251
