### ISSUE TITLE
Too much problem

### ISSUE THREAD

**Issue by hakanoktay** [crucialfelix/django-ajax-selects#256]
the documentation are weird and the example app cannot be run.
>> from django.utils.encoding import python_2_unicode_compatible

i understand django in few days but i haven't understood this for the last two days !

**Comment by crucialfelix** [comment]
The most recent version supports Django 3 and Python 3. It looks like I did not test the example app. I will fix. 
Thanks for the report.

This app may support more features than you need. Be sure to check other apps that may solve the same problem.

**Comment by crucialfelix** [comment]
Fixed a676fafaf0fa3f9dd2fcbfc5b5a4529be15bc269
