### ISSUE TITLE
Popup not closing Django 3.1.1

### ISSUE THREAD

**Issue by breduin** [crucialfelix/django-ajax-selects#274]
Using Django 3.1.1
In fact, the problem is the same as in https://github.com/crucialfelix/django-ajax-selects/issues/176 , so that I've just copied the text.

_Installed ajax-selects and everything works fine except that when I click +add in admin foreign key fields (or M2M key fields) I get the popup window, fill it, click save and it doesn't disappear, staying blank with
popup closing... in the head
it can be closed manually and finally it creates the foreign object, but doesn't link it to the one i was editing_

Those time the problem was solved by downgrading to Django 1.9, but today it's definitely not the best idea ))

**Comment by crucialfelix** [comment]
Fixed in https://github.com/crucialfelix/django-ajax-selects/commit/73de2febb883bdd3312ff85180b30a62f8a662b2

**Comment by breduin** [comment]
Thank you very much for fast commit! Works fine.

**Comment by crucialfelix** [comment]
Sure thing! I must admit there aren't good tests for the frontend against
all Django versions. It could use cypress e2e tests
