### ISSUE TITLE
leftover ')' in urls.py

### ISSUE THREAD

**Issue by Steckelfisch** [crucialfelix/django-ajax-selects#280]
at line 6. (latest version)

not a show stopper if the channel name is generaated, but is if a hard-coded name is used.

**Comment by molt2020** [comment]
I just installed this package with pip and the 'leftover )' is still there! Spent a couple of hours trying to figure out why the library is not working :)

**Comment by crucialfelix** [comment]
I'm sorry I did forget to do the release. 2.1.0 is now out with the fix.

Really sorry you lost a few hours there!
