### ISSUE TITLE
How to customize Widger from textbox to dropdownlist

### ISSUE THREAD

**Issue by technqvi** [crucialfelix/django-ajax-selects#285]
Hi

As I tried  your djaogn-ajax-selects.  Widget is textbox which it is proper for models.CharField in models.py
but my requirement is that I wnat to apply it to  models.ForeignKey as dropdownlist.
dropdownlist consists of  value(id) and text  , I need to use id field to save into database

### **Please advise how to customize your package by  modifying  Widger from textbox to dropdownlist**

![image](https://user-images.githubusercontent.com/38780060/118019702-7a5dfe00-b383-11eb-81c1-d629a8c42d44.png)

I anticipate  displaying as dropdown list as below
```
<select name="employees" id="employees">
  <option value="1">Peter Alunee</option>
  <option value="2">Peter Ones</option>
  <option value="2">Peter Ones</option>
  <option value="3">Tony Wsm</option>
</select>
```

Thank you

**Comment by crucialfelix** [comment]
The search field is indeed a text widget.  The item the user selects is sorted in the database as a foreign key, just as you want.

The select widget (Drop-down) is included, you don't have to implement anything at all or customize anything.

Follow the install instructions carefully and maybe try the included example app.

**Comment by technqvi** [comment]
Thank you for your quick reply.

I have couple questions to ask you.
But I am out of home so I'm not comfortable to write email to ask this question, because I don't have laptop right now

 If you have some time in the next two hour.
Can you reply this question to answer me ?

If so, I will hurry to go back home to write email to ask me.

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by technqvi** [comment]
> The search field is indeed a text widget. The item the user selects is sorted in the database as a foreign key, just as you want.
> 
> The select widget (Drop-down) is included, you don't have to implement anything at all or customize anything.
> 
> Follow the install instructions carefully and maybe try the included example app.

I have a couple of questions to ask you.
I show you my simple data model.

Given data model as code below ,Employee is foreign key   of  Incident , you see models.py as below 
```
class Employee(models.Model):

    employee_name = models.CharField('Engineer Name', max_length=255)

class Incident_Detail(models.Model):

    employee=models.ForeignKey(Employee,on_delete=models.CASCADE,verbose_name='Employee')

    task_start = models.DateTimeField('Task Start')
    task_end = models.DateTimeField('Task End', null=True, blank=True)
    workaround_resolution = models.TextField('Resolution Description')

```

**### _In Adding Form_** 
I implemented clean_employee(self) method further  in order to  take employee name from textbox for retrieving Employee object from database via Django QuerySet  in order that    Incident_Detail data  will be saved  into the database on views.py

**_you can see the screenshot and code below, just so simple. Focusing on def clean_employee(self):_**
 
```

class  Incident_DetailForm(forms.ModelForm):

    employee = AutoCompleteField('employee_names')
    class Meta:
        model= Incident_Detail
        fields = '__all__'
    
    def clean_employee(self):
        employee_name = self.cleaned_data['employee'] # string value from  autocomplete  widget
        employee_obj = Employee.objects.filter(employee_name=employee_name).first()
        if employee_obj is None:
          raise ValidationError(f"Not found {employee_name}")
        return    employee_obj 
```
![image](https://user-images.githubusercontent.com/38780060/118126014-e8f19900-b421-11eb-8bd2-a1e2b5e52558.png)

### My problem describes as below.
**_From what you seen in Updating Form as figure below.  the form show employee ID instead.
I want the form show employee name   in order that after submitting to update . it will use the same way as adding form._**

How to deal with this issue.

![image](https://user-images.githubusercontent.com/38780060/118126460-9664ac80-b422-11eb-8176-443b1f37209e.png)
