### ISSUE TITLE
Django-ajax-selects and Django Rest Framework

### ISSUE THREAD

**Issue by fabiociotoli** [crucialfelix/django-ajax-selects#293]
Does django-ajax-selects work with django rest framework?

Drf uses serializers and not forms so widgets cannot be defined - in this case is there any way to use it?

Thanks

**Comment by crucialfelix** [comment]
I don't think so, no.  I used DRF a little bit earlier this year. It's a REST framework, so the UI is entirely up to the frontend application. There is no connection to the Django admin (which django-ajax-selects is based on)
