### ISSUE TITLE
Not sure what Tag is.

### ISSUE THREAD

**Issue by prisoneer** [crucialfelix/django-ajax-selects#295]
Hi, 

Can anyone explain what Tag is? I'm looking at the documentation but I can't really understand what it's supposed to be.

Thanks in advance for your time.

```python
# yourapp/lookups.py
from ajax_select import register, LookupChannel
from .models import Tag

@register('tags')
class TagsLookup(LookupChannel):

    model = Tag

    def get_query(self, q, request):
        return self.model.objects.filter(name__icontains=q).order_by('name')[:50]

    def format_item_display(self, item):
        return u"<span class='tag'>%s</span>" % item.name
```

**Comment by crucialfelix** [comment]
It's an example model for the common situation where you have a lot of Posts and you want to assign Tags to each post. It's a classic one to many example.

A Tag is like a label in a CMS or blogging platform. 

https://wordpress.com/support/posts/tags/
