### ISSUE TITLE
bug? add new item, initialize inline item with django-nested-admin

### ISSUE THREAD

**Issue by hungphamvn** [crucialfelix/django-ajax-selects#296]
Hi there,
I'm using django-ajax-selects with nested admin inline, and it's working with pre-loading data.
But seems to have a problem when I add a brand new item.
Can anyone support me a bit with this.

Many thanks!

**Comment by crucialfelix** [comment]
Is django-nested-admin a package or django app?  Does the add new item work with normal admin items?

What versions of Django and django-ajax-selects are you using?

**Comment by crucialfelix** [comment]
See #297

**Comment by crucialfelix** [comment]
I think this was fixed along with #297 

Release coming shortly

**Comment by crucialfelix** [comment]
Please reopen if you find that this isn't fixed.
