### ISSUE TITLE
Admin in dark mode = trash/delete/remove icon invisible

### ISSUE THREAD

**Issue by dmwyatt** [crucialfelix/django-ajax-selects#299]
Dark mode:

![image](https://github.com/crucialfelix/django-ajax-selects/assets/163359/645d6c7e-7fd4-4fb8-9c5d-f269505093fb)

Light mode:

![image](https://github.com/crucialfelix/django-ajax-selects/assets/163359/1d15fb32-e7fe-4436-97ce-66177750db37)

**Comment by dmwyatt** [comment]
I guess these icons come from jQuery?  If so, it looks like there's not a way to change the icon color easily. I guess we'd have to bundle an icon for this and save it in a dark and light color.

**Comment by crucialfelix** [comment]
Yeah, jQuery UI is pre-dark mode.  

In general it makes the most sense to build a separate package that solves this problem using modern tooling and libraries. There isn't much point trying to drag jQuery UI into the future for ever.

You may be able to do a CSS image transform. It may not look perfect, but it could look okay.

**Comment by dmwyatt** [comment]
I ended up overriding base_site.html by placing the following in `templates/admin` (assuming you have templates look up setup correctly).

```
{% extends "admin/base_site.html" %}

{% block extrahead %}
  <style>
      @media (prefers-color-scheme: dark) {
          .ui-icon {
              filter: invert(.8);
          }
      }
  </style>
{% endblock %}
```

So I end up with:

![image](https://github.com/crucialfelix/django-ajax-selects/assets/163359/313c1055-41bb-4214-a699-2b9e28878a8e)

**Comment by crucialfelix** [comment]
That's not bad at all. Better than nothing. If you can, make a PR. Otherwise I'm overdue (and over busy) to do another fix and a new release.

**Comment by gidantribal** [comment]
Hello,
In the official docs it's stated that you can change the icon and the CSS if needed, overriding the default one. It may be another workaround...

https://django-ajax-selects.readthedocs.io/en/latest/Media-assets.html

**Comment by crucialfelix** [comment]
Fixed. Thanks for the css!

![Screenshot 2023-12-06 at 4 21 17 PM](https://github.com/crucialfelix/django-ajax-selects/assets/218738/05395321-404b-4cd3-942a-577baf7f7116)
