### ISSUE TITLE
the 3.0.0 release broke 2.2.0 for older python

### ISSUE THREAD

**Issue by topletal** [crucialfelix/django-ajax-selects#306]
We are running a python 3.9 project and using django-ajax-selects. 
We have pinned version 2.2.0 in requirements.txt.
After the release of 3.0.0 version, our build pipeline now fails with `ERROR: Package 'django-ajax-selects' requires a different Python: 3.9.16 not in '<4.0,>=3.10'`
I believe it is because of the change in requirements, which increased the minimum python version to 3.10. ([here](https://github.com/crucialfelix/django-ajax-selects/compare/v2.2.0...v3.0.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R148))
However I am not sure why this affects the 2.2.0 version

**Comment by topletal** [comment]
Could it be potentially because of this mislabeling [here](https://github.com/crucialfelix/django-ajax-selects/compare/v2.2.0...v3.0.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R3) or [here](https://github.com/crucialfelix/django-ajax-selects/compare/v2.2.0...v3.0.0#diff-e3ff9fe466e020dde3a7c0de0b79d5d3899c15395f6765c73bfde54dc2369220R2) ?

**Comment by jackkinsella** [comment]
Is it possible that the changes were released under 2.2.0?

This broke our build 

```
  File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 113, in hashed_name
remote:            raise ValueError(
remote:        ValueError: The file 'ajax_select/vendor/jquery-ui-1.13.2/"images/ui-icons_555555_256x240.png"' could not be found with <mysite.custom_storages.ManifestStorage object at 0x7eff95824390>.
remote: error Command failed with exit code 1.
```

**Comment by gabrielsc1998** [comment]
For now I'm going to use version 2.1.0, it's working here for me.

**Comment by jackkinsella** [comment]
BTW appreciate the maintenance effort here Chris. Thank you

**Comment by crucialfelix** [comment]
I'm looking into this right now.   It's possible that the poetry github action uploaded it to the 2.2.0 release.  It was the first time I ran it, and it threw an error so I assumed it didn't actually do it.

**Comment by crucialfelix** [comment]
@jackkinsella I wonder why there are quotes in the error string:

remote:        ValueError: The file 'ajax_select/vendor/jquery-ui-1.13.2/"images/ui-icons_555555_256x240.png"' could not be found with <mysite.custom_storages.ManifestStorage object at 0x7eff95824390>.

That seems strange

**Comment by vinodpandey** [comment]
We are also facing the same issue. We updated to 2.2.1 to resolve this. 

@crucialfelix it seems during the release for 3.0.0 the METADATA for release 2.2.0 got updated incorrectly. Those source files for 2.2.0 in pypi are still old (april 2022 version). Below is my analysis.

I created a new virtual environment and installed the version 2.2.0 in verbose mode to check where the file was getting downloaded from.

```
pip install --no-cache-dir --verbose django-ajax-selects==2.2.0
```

below was the error:

```
ERROR: Package 'django-ajax-selects' requires a different Python: 3.8.10 not in '<4.0,>=3.10'
Exception information:
Traceback (most recent call last):
  File "/Users/vinodpandey/Projects/temp/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "/Users/vinodpandey/Projects/temp/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/vinodpandey/Projects/temp/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 377, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('<4.0,>=3.10'), parent=LinkCandidate('https://files.pythonhosted.org/packages/68/5e/2749c43efcda82be110b41b278f51a03ef8b303287ac8590552ca32f3bba/django_ajax_selects-2.2.0-py3-none-any.whl#sha256=2e52130e85c8ead5429e2d8cb4907b77fafda8faed82484f9c6a51451846f608 (from https://pypi.org/simple/django-ajax-selects/)'))]
```

I downloaded the file https://files.pythonhosted.org/packages/68/5e/2749c43efcda82be110b41b278f51a03ef8b303287ac8590552ca32f3bba/django_ajax_selects-2.2.0-py3-none-any.whl#sha256=2e52130e85c8ead5429e2d8cb4907b77fafda8faed82484f9c6a51451846f608 

The version in `ajax_select/__init__.py` is correct

```
"""JQuery-Ajax Autocomplete fields for Django Forms."""
__version__ = "2.2.0"
__author__ = "crucialfelix"
__contact__ = "crucialfelix@gmail.com"
__homepage__ = "https://github.com/crucialfelix/django-ajax-selects/"
```

But the metadata file `django_ajax_selects-2.2.0.dist-info\METADATA` has 

```
Requires-Python: >=3.10,<4.0
Requires-Dist: Django (>=3.2)
``` 

The workflow didn't overwrite the older package, but rewrote the METADATA.

**Comment by crucialfelix** [comment]
@vinodpandey Thanks for investigating.  

Now I see what's happened. Previously I only released sdist for 2.2.0  
When I accidentally triggered a release with the wrong version, it correctly blocked the duplicate sdist, but it still published the .whl wheel

The one you downloaded is actually 3.0.0 but the version number was wrong.

I'm going to try the build number trick that @topletal linked to see if that can fix 2.2.0 releases

**Comment by crucialfelix** [comment]
2.2.0 is fixed now!

It turns out that:
- You can upload alternate versions for a release by using a build number:  django_ajax_selects-2.2.0-2-py3-none-any.whl
- You can delete uploaded packages on pypi

**Comment by infr** [comment]
I can verify that it works again, thank you @crucialfelix !
