### ISSUE TITLE
v3.0.0 AutoCompleteSelectMultiple Add New not working with Django 4.2.8 nor 5.0.0

### ISSUE THREAD

**Issue by kalevhark** [crucialfelix/django-ajax-selects#307]
AutoCompleteSelectMultiple Add New not working with Django 4.2.8 nor 5.0.0.
Installed in clean virtual environment Django 5.0, django-ajax-selects 3.0.0 and django-ajax-selects example app.
My steps in admin view:
1. Add Group
2. Name -> "Some Group"
3. Members -> click on "+ add"
4. Popup opens, and after entering data click on "SAVE"
5. Popup closes but Members list is empty
6. If I click on "Save and continue editing" new member appears in list
7. If I try to add new one, nothing happens again but if I click on "Save and continue editing" it _replaces_ existing list not adds new member.

I tried in Amazon EC2 instance and in MS Windows 10 machine. Tried with Django 4.2.8 and 5.0 but same.

* Python 3.10.2 virtual environment
* Django 4.2.8 or 5.0
* django-ajax-selects

**Comment by kalevhark** [comment]
I found a partial solution.
In ajax_select.js added some code:

 $(document).ready(function () {
  
  // added section
  window.dismissAddRelatedObjectPopup = function (win, newId, newRepr) {
    const name = win.name.split("__")[0];
    const elem = document.getElementById(name);
    if (elem) {
      const elemName = elem.nodeName.toUpperCase();
      if (elemName === 'INPUT') {
        if (elem.classList.contains('vManyToManyRawIdAdminField') && elem.value) {
          elem.value += ',' + newId;
        } else {
	  elem.value = (elem.value ? elem.value : "|") + newId + "|";
        }
      }
      win.close();
  }
  // end of added section
  [...]

})(window.jQuery);

but everytime after addng a new item it's needed to click "Save and countinue editing". After that new item appears in items list.

**Comment by kalevhark** [comment]
I figured out solution for me. In ajax_select.js added some extra code:

[...]
$(document).ready(function () {
  \\ extra code goes here
  [...]
})(window.jQuery);

Modified ajax_select.js:
[ajax_select.js.txt](https://github.com/crucialfelix/django-ajax-selects/files/13641318/ajax_select.js.txt)

**Comment by crucialfelix** [comment]
Are you using this in the Django admin or on a separate page?  It looks like your fix is going to overwrite Django's existing function (if running in admin):

```js
  $(document).ready(function () {

    // extra code for add new fix
    window.dismissAddRelatedObjectPopup = function (win, newId, newRepr) {
```

**Comment by kalevhark** [comment]
I'm using Django admin.
Maybe I figured out what is wrong with v3.0.0 ajax_select.js in Django 4.2.8/5.0:
ajax_select.js code in lines 187-209 must by inside
$(document).ready(function () {
<-- here
[...]
});

except:
var input = $("#" + win.name);
must be:
var input = $("#" + win.name.split('__')[0]);

Proposed solution of ajax_select.js attached.
Sorry about my weak knowledge of Javascript!

[ajax_select.txt](https://github.com/crucialfelix/django-ajax-selects/files/13652513/ajax_select.txt)

**Comment by crucialfelix** [comment]
It was working fine for me and for other people, but obviously there is still something wrong.  

jQuery is included, and if it wasn't then you couldn't do `$(document).ready`

I will investigate and get a fix asap.

Thanks!

**Comment by crucialfelix** [comment]
Django changed the naming of the popup window.  This is why the handler function didn't catch the callback that updates the inputs.

The other issue was that there are two jquery: Django's and ajax_selects. It's not wise to use Django's, and it only works in the admin. But it does mean having to do a separate wait on `djangoJQuery(document).ready(function () { ` before it can patch the django admin window closer function.

I tried to switch to using the Django's `input.on("changed", ...)` event handler, but it doesn't get the id nor the string repr.

**Comment by crucialfelix** [comment]
Release tommorrow
