### ISSUE TITLE
Does not work with jquery-ui >= 1.10.2

### ISSUE THREAD

**Issue by brianmay** [crucialfelix/django-ajax-selects#42]
I haven't yet had a chance to investigate in full detail, but noticed when I upgraded to:

http://code.jquery.com/jquery-1.9.1.js
http://code.jquery.com/ui/1.10.2/jquery-ui.js

I get the error:

Uncaught TypeError: Cannot set property '_renderItem' of undefined

As this same code works fine with previous versions of jquery and jquery-ui, I am assuming that something has changed to break this.

Alternatively, I might have broken something too... Need to double check.

**Comment by RobertoMaurizzi** [comment]
Any news on this? Did they decide on a stable and documented API for JQuery versions >= 1.11 yet? :-)
I'd guess that by now most people are already at 1.11+ or 2.x+
