### ISSUE TITLE
Field appers duplicated when marked as readonly in admin

### ISSUE THREAD

**Issue by lvella** [crucialfelix/django-ajax-selects#84]
I have a field that can only be selected upon creation, so I am using the technique described in http://stackoverflow.com/a/4346448/578749 to make it readonly when editing:

```python
class MyModelAdmin(admin.ModelAdmin):
    #...
    def get_readonly_fields(self, request, obj=None):
        if obj: # editing an existing object
            return self.readonly_fields + ('my_ajax_field')
        return self.readonly_fields
```

The problem is that the AJAX field, from a form created with `make_ajax_form`, appears duplicated when changed to readonly like this.

**Comment by crucialfelix** [comment]
This is really a Django bug I think. I can confirm what you are seeing.

```python
class SongAdmin(AjaxSelectAdmin):

    form = make_ajax_form(Song, {'group': 'group', 'title': 'cliche'})
    # django bug:
    # readonly_fields = ('group',)
    # django displays group twice if its listed as a readonly_field
    # and throws a validation error on save
    # but doesn't show any error message to the user

admin.site.register(Song, SongAdmin)
```

I think what happens is that by using `make_ajax_form` you are creating a form with an explicit field. By using `readonly_fields` you are again referencing the field by name.  Django then iterates through both lists.

There isn't anything I can do to hack Django admin to avoid that.

**Comment by crucialfelix** [comment]
I just ran into this myself again where there is no django-ajax-selects involved.

When you have a custom form for an admin, then you have to configure the read_only on the form, not on the admin. Otherwise you get the field shown twice

```python
class MyModelForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields["slug"].widget.attrs["readonly"] = True
```
