### ISSUE TITLE
Inline won't work with new lines (SOLVED)

### ISSUE THREAD

**Issue by AmirTugi** [crucialfelix/django-ajax-selects#87]
Hi,
Recently I've been having troubles with django-ajax-selects and inline forms.
The problem was, that when I add a new line it ajax-selects wont bind to it.
I spent hours for searching the cause in the internet, and maybe fixes. I only found that this issue was once a problem, but now resolved (and from the documentation django-ajax-selects should work with inlines).
So, I started debugging the code.
What I found is that django-ajax-selects DOES bind new lines when you click the 'add another' link, and this code is in the $(document).ready(); function.
However, by alerting one line above this call I saw that the 'add another' link was not yet built. So the binding to the link won't catch.
What I did to fix this issue was to to change the 'on' event to 'delegate' so future selectors (like our 'add another') would be bound.

In ajax_selects.js change lines 206-209 with these:

$('body').delegate( '.inline-group ul.tools a.add, .inline-group div.add-row a, .inline-group .tabular tr.add-row td a', 'click', function() {
      $(window).trigger('init-autocomplete');
    });

**Comment by funkyfuture** [comment]
@AmirTugi why did you close this issue?

i found that your proposal made the functionality work in my case though the contributed code does actually comply with jQuery1.7+
