### ISSUE TITLE
callbacks for select doesn't work

### ISSUE THREAD

**Issue by mdomans** [crucialfelix/django-ajax-selects#97]
It seems that when a choice is selected from the drop down a callback "added" should be triggered, but I'm unable to bind my code to it, neither binding like this:
 ```$("#{{ html_id }}").bind('added', function(){})```

or this:
```$("#{{ html_id }}_on_deck").bind('added', function(){})```

Is this by design or this a bug? Or am I doing smth wrong?

**Comment by onyekaa** [comment]
For what it's worth, my callbacks aren't working either. They were before, but I moved my files to a new install and reinstalled my all my third party apps and the callbacks have stopped working. Nothing I do works.

**Comment by unklphil** [comment]
It works for me when I add the listener on `$('#id_' + field + '_wrapper')`
