### ISSUE TITLE
Support reverse relationships

### ISSUE THREAD

**Issue by jschneier** [crucialfelix/django-ajax-selects#99]
hi and thanks for the great project! I'd like to be able to query from the M2M on the other side of the relationship in the admin which doesn't currently work in master. Give me a second and I'll put up a patch.

**Comment by crucialfelix** [comment]
interesting. can you show some example with simple models ? the best would be to add it to the example app so I can test them in various djangos.

also some addition to the documentation is needed for this to be complete.

thanks !

**Comment by jschneier** [comment]
See comment on #100.
